### ISSUE TITLE
Improved Syntax for Custom Attributes

### ISSUE THREAD

**Issue by jcreedon** [terraform-providers/terraform-provider-vsphere#370] opened 2018-01-24 20:03 UTC
I'm very excited to finally have custom attributes for vsphere in terraform. However the syntax is annoying if you want to do more than one custom attribute. Either you have to deal with a very long string or a here doc.

(Sorry if the below formatting isn't right, I wasn't sure the best way to shoe horn a feature request into the issue template.)

### Terraform Version

`Terraform v0.11.2`

### vSphere Provider Version

`provider.vsphere v1.2.0`

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`
- Any other resource listed in https://www.terraform.io/docs/providers/vsphere/r/custom_attribute.html#managed-object-types

### Terraform Configuration Files

Per the documentation, this format should be used for specifying custom attrbiutes

```hcl
resource "vpshere_virtual_machine" "web" {
  ...

  custom_attributes = "${map(vsphere_custom_attribute.attribute.id, "value")}"
}
```

### Desired Behavior

Something reasonable like how tags work with the AWS provider would be fantastic, like:

```hcl
  custom_attributes {
    app = "appname"
    envname = "${var.envname}"
    role = "web"
    shortenv = "${var.shortenv}"
  }
```

### Important Factoids

I think there also might be a bug in the HCL or HIL parser. What I end up having to use is:

```hcl
  custom_attributes = <<EOF
${map(
data.vsphere_custom_attribute.attribute-app.id, "appname",
data.vsphere_custom_attribute.attribute-envname.id, "${var.envname}",
data.vsphere_custom_attribute.attribute-role.id, "web",
data.vsphere_custom_attribute.attribute-shortenv.id, "${var.shortenv}"
)}EOF
```

However idiomatic here docs (as [specified by bash](https://www.gnu.org/software/bash/manual/bashref.html#Here-Documents)) should be written as such:

```hcl
  custom_attributes = <<EOF
${map(
data.vsphere_custom_attribute.attribute-app.id, "appname",
data.vsphere_custom_attribute.attribute-envname.id, "${var.envname}",
data.vsphere_custom_attribute.attribute-role.id, "web",
data.vsphere_custom_attribute.attribute-shortenv.id, "${var.shortenv}"
)}
EOF
```

With the termination token on it's own line. However in this situation, terraform throws the following error:

```
Error: vsphere_virtual_machine.web: 1 error(s) occurred:

* vsphere_virtual_machine.web: At column 1, line 1: output of an HIL expression must be a string, or a single list (argument 1 is TypeMap) in:

${map(
data.vsphere_custom_attribute.attribute-app.id, "appname",
data.vsphere_custom_attribute.attribute-envname.id, "${var.envname}",
data.vsphere_custom_attribute.attribute-role.id, "web",
data.vsphere_custom_attribute.attribute-shortenv.id, "${var.shortenv}"
)}
```

As a stopgap, if HCL could support the `<<-` syntax, that would help cleanup some of the mess because then you could at least indent it like this:

```hcl
  custom_attributes = <<-EOF
    ${map(
    data.vsphere_custom_attribute.attribute-app.id, "appname",
    data.vsphere_custom_attribute.attribute-envname.id, "${var.envname}",
    data.vsphere_custom_attribute.attribute-role.id, "web",
    data.vsphere_custom_attribute.attribute-shortenv.id, "${var.shortenv}"
    )}
    EOF
```

**Comment by vancluever** [comment] 2018-01-25 17:14
@jcreedon the awkward tagging interface here is due to how vSphere works with tags versus AWS. In AWS, tags are simple key/value pairs, in vSphere, they there are more complicated pre-configured data sets that need to be attached to objects via their IDs. We we have a framework in the vSphere provider of allowing as little arbitrary data as possible in downstream resources, you first either have to create the attribute with the `vsphere_custom_attribute` resource, or fetch its data with the counterpart data source if it exists already, and then reference its id in the appropriate resource.

As for the HIL issues, that could definitely be cleaned up. I'm going to check what the right project to open that issue up against would be. We are currently working on a [new version of HCL](https://github.com/hashicorp/hcl2) that is aiming to bring both language structure and interpolation together, so depending on everyone's time and priorities, this might instead be something that gets fixed in HCL2 instead.

Thanks!

**Comment by vancluever** [comment] 2018-01-25 17:54
Hey @jcreedon I just confirmed that since we are focusing on HCL2 that this is more than likely where it will be fixed.

With HCL2, we will be implementing a couple of things that pertain to what you are trying to do here:

* Functions will no longer require quoting in strings or the HIL enclosure (`"${}"`), so you will be able to use the `map` function directly, properly indented.
* Even better, we will be supporting a proper map syntax. This means you would be able to write something like (note: not necessarily final form):

```
# NOT YET IMPLEMENTED and may change before final release
  custom_attributes = {
    "${data.vsphere_custom_attribute.attribute-app.id}"      = "appname"
    "${data.vsphere_custom_attribute.attribute-envname.id}"  = var.envname
    "${data.vsphere_custom_attribute.attribute-role.id}"     = "web"
    "${data.vsphere_custom_attribute.attribute-shortenv.id}" = var.shortenv
  }
```

HCL2 is a priority for the Terraform Core team, and while there is no official release date or specific feed that progress can be tracked on, you can watch the [Core project](https://github.com/hashicorp/terraform) for updates on its incorporation into Terraform itself.

Thanks!

**Closed by vancluever** 2018-01-25 17:54 UTC
Labels: enhancement, question

**Comment by jcreedon** [comment] 2018-01-25 18:08
HCL2 looks to be the right solution. I look forward to seeing it. Thanks!
