### ISSUE TITLE
Disk label, vsphere_virtual_machine: diffs didn't match during apply.

### ISSUE THREAD

**Issue by marekmrowca** [terraform-providers/terraform-provider-vsphere#527] opened 2018-05-15 08:38 UTC
Hi,
terraform crashes when trying to change vm's name and apply.
I created one VM with terraform and than changed its name (disk name, computer name).
The name is tftemplate.
Here is the output of "terraform plan" before appying this change, grepped by the name "tftemplate":
```
     clone.0.customize.0.windows_options.0.computer_name:     "tftemplate35" => "tftemplate20" (forces new resource)
      disk.0.label:                                            "tftemplate35.vmdk" => "tftemplate20.vmdk"
      disk.0.path:                                             "e496fa5a-88fb-2263-cdb7-1418773b5422/tftemplate35.vmdk" => <computed>
      disk.1.label:                                            "" => "tftemplate20.vmdk"
      folder:                                                  "Terraform/tftemplate" => "Terraform/tftemplate"
      name:                                                    "tftemplate35" => "tftemplate20"
      vmx_path:                                                "e496fa5a-88fb-2263-cdb7-1418773b5422/tftemplate35.vmx" => <computed>

```

When I "terraform apply" this it will crash with the following info:
```
...
vsphere_virtual_machine.tfvm: Still destroying... (ID: 423c9e0f-68aa-09bf-ccd2-a20912b8e7ec, 10s elapsed)
vsphere_virtual_machine.tfvm: Destruction complete after 13s

Error: Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.tfvm: vsphere_virtual_machine.tfvm: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.7
    Resource ID: vsphere_virtual_machine.tfvm
    Mismatch reason: attribute mismatch: disk.1.attach
...
```

Environment:
```
Terraform v0.11.7
+ provider.null v1.0.0
+ provider.openstack v1.3.0
+ provider.vsphere v1.3.3
```

Best regards,
Marek

**Comment by jason-azze** [comment] 2018-11-20 15:20
I have observed this bug in TF `0.11.10` as well. I am also causing my VMs to be renamed. In my case (a bunch of CentOS 6 machines) I'm dropping the CentOS minor version number from my naming convention. So, for example, `cent69-da100` will become `cent6-da100`.

The section of the plan involving disks looks like:
```
      disk.#:                                           "1" => "1"
      disk.0.attach:                                    "false" => "false"
      disk.0.datastore_id:                              "datastore-259" => "<computed>"
      disk.0.device_address:                            "scsi:0:0" => <computed>
      disk.0.disk_mode:                                 "persistent" => "persistent"
      disk.0.disk_sharing:                              "sharingNone" => "sharingNone"
      disk.0.eagerly_scrub:                             "false" => "false"
      disk.0.io_limit:                                  "-1" => "-1"
      disk.0.io_reservation:                            "0" => "0"
      disk.0.io_share_count:                            "1000" => "0"
      disk.0.io_share_level:                            "normal" => "normal"
      disk.0.keep_on_remove:                            "false" => "false"
      disk.0.key:                                       "2000" => "0"
      disk.0.label:                                     "cent69-da103.vmdk" => "cent6-da103.vmdk"
      disk.0.path:                                      "cent69-da103/cent69-da103_1.vmdk" => <computed>
      disk.0.size:                                      "350" => "350"
      disk.0.thin_provisioned:                          "true" => "true"
      disk.0.unit_number:                               "0" => "0"
      disk.0.uuid:                                      "6000C299-af44-7924-e24a-2eb231863847" => <computed>
      disk.0.write_through:                             "false" => "false"
      disk.1.attach:                                    "" => "false"
      disk.1.datastore_id:                              "" => "<computed>"
      disk.1.disk_mode:                                 "" => "persistent"
      disk.1.disk_sharing:                              "" => "sharingNone"
      disk.1.eagerly_scrub:                             "" => "false"
      disk.1.io_limit:                                  "" => "-1"
      disk.1.io_reservation:                            "" => "0"
      disk.1.io_share_count:                            "" => "0"
      disk.1.io_share_level:                            "" => "normal"
      disk.1.keep_on_remove:                            "" => "false"
      disk.1.key:                                       "" => "0"
      disk.1.label:                                     "" => "cent6-da103.vmdk"
      disk.1.size:                                      "" => "350"
      disk.1.thin_provisioned:                          "" => "true"
      disk.1.unit_number:                               "" => "0"
      disk.1.write_through:                             "" => "false"
```

And I get the same crash reported by Marek.

```
* module.linux-test.vsphere_virtual_machine.linux[0]: vsphere_virtual_machine.linux.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.10
    Resource ID: vsphere_virtual_machine.linux.0
    Mismatch reason: attribute mismatch: disk.1.attach
```
The old VMs are destroyed. The crash happens on the attempted creation of replacements.

To work around this, I simply run a new plan and apply it. The VMs are then created with the new names.

Here's a gist with more output: https://gist.github.com/jason-azze/6328636bd90fd56fa6fc120748b5a808

**Comment by bill-rich** [comment] 2019-06-26 06:22
Same root cause as #357. Closing to track the issue there.

**Closed by bill-rich** 2019-06-26 06:22 UTC
Labels: bug
