### ISSUE TITLE
Deleting a VMFS datastore fails

### ISSUE THREAD

**Issue by sofixa** [terraform-providers/terraform-provider-vsphere#548] opened 2018-06-08 15:03 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version

terraform 0.11

### vSphere Provider Version

terraform-provider-vsphere ~> 1.3.3 

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_vmfs_datastore`

### Terraform Configuration Files

```hcl
data "vsphere_vmfs_disks" "pa3_available" {
  provider       = "vsphere.pa3"
  count          = "${var.site == "pa3" || var.site == "pam" ? 1 : 0 }"
  depends_on     = ["solidfire_volume.pa3_volume"]
  host_system_id = "${data.vsphere_host.pa3_hosts.*.id[0]}"
  rescan         = true
  filter         = "${solidfire_volume.pa3_volume.scsi_naa_device_id}"
}

resource "vsphere_vmfs_datastore" "pa3_datastore" {
  provider       = "vsphere.pa3"
  count          = "${var.site == "pa3" || var.site == "pam" ? 1 : 0 }"
  name           = "pa3-${var.client}-01"
  host_system_id = "${data.vsphere_host.pa3_hosts.*.id[0]}"
  folder         = "${vsphere_folder.pa3_client_datastores.path}"
  disks          = ["${data.vsphere_vmfs_disks.pa3_available.disks}"]
}

data "vsphere_vmfs_disks" "pa3_rescan" {
  provider       = "vsphere.pa3"
  count          = "${var.site == "pa3" || var.site == "pam" ? length(data.vsphere_host.pa3_hosts.*.id) : 0 }"
  depends_on     = ["vsphere_vmfs_datastore.pa3_datastore"]
  host_system_id = "${data.vsphere_host.pa3_hosts.*.id[count.index]}"
  rescan         = true
  filter         = "${solidfire_volume.pa3_volume.scsi_naa_device_id}"
}

```

### Debug Output

When trying to delete via terraform:
```
Error: Error applying plan:

1 error(s) occurred:

* module.client-oliverstore-pp-pa3.vsphere_vmfs_datastore.pa3_datastore (destroy): 1 error(s) occurred:

* vsphere_vmfs_datastore.pa3_datastore: could not delete datastore: ServerFaultCode: An error occurred during host configuration.

```

After manually doing a rescan via vSphere Web Client which "deletes" the datastore(it's no longer present because the underlying iSCSI device has been deleted by the same terraform module that manages the vsphere datastore), it deletion fails because the datastore is already gone:

```
* module.client-pp-pa3.vsphere_vmfs_datastore.pa3_datastore: vsphere_vmfs_datastore.pa3_datastore: cannot find datastore: ServerFaultCode: The object 'vim.Datastore:datastore-1600' has already been deleted or has not been completely created
```

### Expected Behavior

The datastore be deleted / rescaned which would delete it and remove it from the tfstate.

### Actual Behavior

Neither scan removed the datastore (depends_on only doesn't seem to be triggered after destroy or maybe i'm mistaken?), and after manually doing a scan which removed it, terraform fails in getting the datastore because it's already deleted (so even if terraform had managed to scan and remove the datastore, it would have failed to destroy the resource). 

IMHO, we either need to do things in a different order (first delete the datastore, then delete the underlying volume) which i don't see how to do with terraform OR somehow get the datasource vmfs_disks to trigger post-destroy. 

Also, i think destroying the resource shouldn't fail if the resource is already deleted ^^

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. Create and present an iSCSI volume with terraform
2. `terraform apply` with the aforementioned hcl that adds a datastore on top of said underlying volume
3. Delete said volume with terraform
4. `terraform apply` to destroy the datastore
5. It fails (even via the interface the datastore can't be deleted)
6. Rescan manually to remove the datastore
7. re-apply to destroy the datastore
8. It fails because "has already been deleted or has not been completely created"

Cheers,
Adrian

**Comment by sofixa** [comment] 2018-06-20 09:48
@bill-rich i'd qualify it more as a bug (terraform failing to delete a deleted object) + a question (why didn't it delete it in the first place?)

**Comment by vancluever** [comment] 2018-06-20 13:43
@sofixa indeed, at the very least the next refresh should remove this from the state. I'm not too sure how much we can prevent this (the exact root cause may be hard to track down as we actually have tests for these cases which pass generally without issue), but the refresh behavior is something we can adjust for sure.

**Comment by sofixa** [comment] 2018-06-22 11:57
@vancluever I've tried it multiple times, so the following should work to reproduce:

* create a VMFS datastore
* delete the underlying volume or make it inaccessible to the ESXi host
* VMware will show it as inaccessible - a delete operation on it will fail (with the same message as doing it via terraform, so it isn't a terraform bug _per se_ )
* an iSCSI rescan will remove the datastore (since its underlying volume is no longer accessible)

However running a rescan via terraform (with the vsphere_vmfs_disks datasource ) doesn't seem to work (we have a bunch of them inside a few modules in our tf configuration, that depend_on volumes and filter by their iscsi naa ids, so maybe due to the filter the "broken" inaccessible volume doesn't get scanned). Hm, that might be a way around the issue, adding an extra scan just in case, i'll go try that and keep you informed. 

In any case though, the refresh failing because something is already deleted when terraform is supposed to delete it is funny xD

Adrian

**Comment by aareet** [comment] 2019-10-10 01:44
@sofixa is this still reproducible in Terraform 0.12 and the latest provider version?

**Comment by aareet** [comment] 2019-11-21 17:04
Closing since it has been 1.5 months since last response. Please reopen if you are able to reproduce.

**Closed by aareet** 2019-11-21 17:04 UTC
Labels: bug, waiting-response
