### ISSUE TITLE
vSphere clone customization hangs

### ISSUE THREAD

**Issue by rrati** [terraform-providers/terraform-provider-vsphere#443] opened 2018-03-27 19:31 UTC
### Terraform Version
Terraform v0.11.5

### vSphere Provider Version
provider.vsphere v1.3.3

### Affected Resource(s)
- vsphere_virtual_machine

If this issue appears to affect multiple resources, it may be an issue with
Terraform's core, so please mention this.

### Terraform Configuration Files
resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 2
  memory   = 1024
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  disk {
    label = "disk1"
    size = "80"
    eagerly_scrub = "false"
    thin_provisioned = "true"
    unit_number = 1
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "terraform-test"
        domain = "cluster.local"
      }

      network_interface {}
    }

  }

  connection {
    type = "ssh"
    user = "username"
    password = "password"
    agent = "false"
  }

  provisioner "file" {
    source = "~/.ssh/id_rsa.pub"
    destination = "~/id_rsa.pub"
  }

  provisioner "remote-exec" {
    inline = [
      "mkdir ~/.ssh", 
      "chmod 755 ~/.ssh",
      "cat ~/id_rsa.pub >> ~/.ssh/authorized_keys",
      "chmod 600 ~/.ssh/authorized_keys",
      "rm -f ~/id_rsa.pub",
      "sudo reboot",
    ]
  }
}

### Expected Behavior

VM should start up in vSphere and be customized with the hostname/domain specified

### Actual Behavior

VM startup hangs, continually waiting for the VM to come up.  Similar behavior to when the networking information is correct.

### Steps to Reproduce
1. `terraform apply`

If the customize stanza is removed, the instance comes up just fine so it isn't a problem with the template.   The relevant information from plan:

  boot_retry_delay:                                 "" => "10000"
  change_version:                                   "" => "<computed>"
  clone.#:                                          "" => "1"
  clone.0.customize.#:                              "" => "1"
  clone.0.customize.0.linux_options.#:              "" => "1"
  clone.0.customize.0.linux_options.0.domain:       "" => "cluster.local"
  clone.0.customize.0.linux_options.0.host_name:    "" => "terraform-test"
  clone.0.customize.0.linux_options.0.hw_clock_utc: "" => "true"
  clone.0.customize.0.network_interface.#:          "" => "1"
  clone.0.customize.0.timeout:                      "" => "10"
...
  network_interface.#:                              "" => "1"
  network_interface.0.adapter_type:                 "" => "vmxnet3"
  network_interface.0.bandwidth_limit:              "" => "-1"
  network_interface.0.bandwidth_reservation:        "" => "0"
  network_interface.0.bandwidth_share_count:        "" => "<computed>"
  network_interface.0.bandwidth_share_level:        "" => "normal"
  network_interface.0.device_address:               "" => "<computed>"
  network_interface.0.key:                          "" => "<computed>"
  network_interface.0.mac_address:                  "" => "<computed>"

The instructions say to use an empty network_interface in customize for dhcp, and if network_interface is removed then vSphere complains that the customization doesn't have the same number of network interfaces.

**Comment by vancluever** [comment] 2018-03-28 16:13
This appears to be a duplicate of #444, closing in favour of that.

**Closed by vancluever** 2018-03-28 16:13 UTC
