### ISSUE TITLE
terraform import vsphere_distributed_port_group does not import vlan_range

### ISSUE THREAD

**Issue by RaceFPV** [terraform-providers/terraform-provider-vsphere#669] opened 2018-12-07 19:23 UTC
### Terraform Version
Terraform v0.11.7

### vSphere Provider Version
provider.vsphere v1.9.0

### Affected Resource(s)
- `vsphere_virtual_machine`
- `vsphere_distributed_port_group`

### Terraform Configuration Files
```
resource "vsphere_distributed_port_group" "pg_100_test" {
  name                            = "VLAN-100-Test"
  distributed_virtual_switch_uuid = "${data.vsphere_distributed_virtual_switch.10GB_VM.id}"
  vlan_id = "100"
  active_uplinks  = ["Uplink 1", "Uplink 2"]
  block_override_allowed = true
  port_config_reset_at_disconnect = true
}
```

### Debug Output
https://gist.github.com/RaceFPV/29c5a60cf33129f7fffef599ae429107

### Expected Behavior
After importing the distributed port group, terraform apply should not have any changes as the configuration file matches 1 to 1 with the current state of the port group.

### Actual Behavior
The port group imported with a missing state field entry, `vlan_range.#`. It then wants to create the missing entry with a computed value. The vlan_range field cannot co-exist with the vlan_id field which already exists in this case.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a pre-existing port group matching the terraform configuration
2. Import the port-group into terraform: `terraform import vsphere_distributed_port_group.pg_100_test /dc1/network/VLAN-100-Test`
2. `terraform apply`

### Important Factoids
None

### References
None

**Comment by RaceFPV** [comment] 2018-12-07 21:59
Attempting to terraform apply while leaving the vlan_range.# field change in place causes an error applying plan, as seen here: https://gist.github.com/RaceFPV/34772b31c623d9970e36030befcde5bd

Modifying the tfstate file to include a blank copy of vlan_range.# at the end of the port group allows terraform to succeed.

**Comment by bill-rich** [comment] 2018-12-08 00:20
@RaceFPV It sounds like `vlan_range` isn't being set properly on `Read` after the import. I do not think it will be too difficult to get a test created to replicate the problem. I will get the fix for the issue on the backlog. In the meantime, I'd recommend just running the `terraform apply` to get the state synced.

**Comment by AirCombat** [comment] 2019-02-13 00:19
I had a similar issue as above importing a distributed virtual switch. I cannot test the affects of hitting apply as there are 1000 VMs running on the DVS so i have backed away slowly and used a data source instead of a resource.

After successfully importing, running terraform plan on another change:
` vsphere_distributed_virtual_switch.CAN-DATA-DVS`
`      vlan_range.#:                      "" => <computed>`

Terraform v0.11.8
+ provider.vsphere v1.9.1

**Comment by RaceFPV** [comment] 2019-02-13 00:30
We have been consistantly importing distributed switches with this bug in place without ill effect in the ~300 vm range. I'd guess we've run through the procedure including the double apply around 30x in production so far fwiw.

**Comment by dannyk81** [comment] 2019-05-14 18:10
We were still hitting this with version 1.10.0, but this looks like it was solved in 1.11.0

**Comment by pillarsdotnet** [comment] 2019-06-04 11:45
The problem still exists in 1.11.0

**Comment by yannfill** [comment] 2019-06-04 15:14
I can confirm @pillarsdotnet comment. standby_uplinks is also no properly imported:
`+ standby_uplinks                        = (known after apply)`
Both vlan_range and standby_uplinks are set to `null` on import. If I modify the tfstate file to set vlan_range to an empty list (` "vlan_range": []`) and standby_uplinks to a list reflecting the one in active_uplinks, nothing is changed on plan.

**Comment by pillarsdotnet** [comment] 2019-06-04 15:21
On the other hand, I discovered that a `vsphere_distributed_port_group` is a special case of a `vsphere_network` which can be referenced via a `data` block.  So if there is no intent to create or modify, the [OP](https://github.com/terraform-providers/terraform-provider-vsphere/issues/669#issue-388782604) can simply write:
```
  data "vsphere_network" "pg_100_test" {
    name                            = "VLAN-100-Test",
    datacenter_id                  = "${data.vsphere_distributed_virtual_switch.10GB_VM.datacenter_id}"
  }
```

**Comment by KevDBG** [comment] 2019-08-28 13:01
Hello,

Any update ? I have the same problem:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ vsphere_distributed_port_group.test
      port_config_reset_at_disconnect: "true" => "false"
      vlan_range.#:                    "" => <computed>


Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by bill-rich** [comment] 2020-04-09 18:56
Closing this for now since there hasn't been a response. If this is still an issue, please let me know and we can re-open it.

**Closed by bill-rich** 2020-04-09 18:56 UTC
Labels: bug, waiting-response
