### ISSUE TITLE
Getting error while creating VM under vAPP resource pool.

### ISSUE THREAD

**Issue by balubalananda** [terraform-providers/terraform-provider-vsphere#810] opened 2019-07-16 15:34 UTC
Terraform v0.11.10

**Comment by bill-rich** [comment] 2019-07-19 03:24
Hi @balubalananda! This is due to the VM's path changing from being under the `vm` tree to being under the `host` tree when it is part of a vApp. There is a condition to handle this when the VM's immediate resource pool is a vApp, but if there is an intermediary resource pool, then the check fails to account for this. I will look into getting a bug fix in for this.

**Comment by aareet** [comment] 2019-09-17 23:59
@balubalananda this issue should be resolved with the next release.

**Comment by balubalananda** [comment] 2019-09-18 15:23
is there anyway, we can this latest fix in our environment ?

**Comment by aareet** [comment] 2019-09-18 16:12
@balubalananda you can create a build from the `master` branch by following the README if you wish

**Comment by balubalananda** [comment] 2019-10-01 16:30
> Terraform v0.11.10
> provider.vsphere: version = "~> 1.12"
> 
> We are getting below error while creating VM under vAPP resource pool.
> 
> • vsphere_virtual_machine.soa: 1 error(s) occurred:
> 
> * vsphere_virtual_machine.soa: error parsing virtual machine path "/Axxxx/host/HA-Hxxx/Resources/JCATVAPP/balutest": could not split path "/Axxx/host/HA-HPxx/Resources/JCATVAPP/balutest" on "/vm"
> 
> The below code is working fine with out any issue when we are using resource pool name ,which is not under Vsphere vAPP
> 
> #####working resource pool name format###
> 
> data "vsphere_resource_pool" "pool" {
> name = "HA-HPxxxx/Resources/HSS_Chef_Test_7.2"
> 
> #name format =<"cluster name>/Resource/
> 
> ###End working resource pool ####
> 
> ###Not working resource pool name format (under vAPP)####
> 
> data "vsphere_resource_pool" "pool" {
> name = "HA-Hxxxxxxxx/Resources/JCATVAPP/testvappresourcepool"
> $nameformat = Resources/<vAPPname/<resourcepoolname"
> 
> #######Not working resource pool code end##########
> 
> ##########Code: ###################
> 
> ```
> provider "vsphere" { 
> ```
> 
> user = "xxxx"
> password = "xxxxxx"
> vsphere_server = "10.3.xxx"
> 
> # if you have a self-signed cert
> allow_unverified_ssl = true
> }
> data "vsphere_datacenter" "dc" {
> name = "Axxx"
> }
> data "vsphere_datastore" "datastore" {
> name = "Txxxx"
> datacenter_id = "${data.vsphere_datacenter.dc.id}"
> }
> data "vsphere_resource_pool" "pool" {
> #name = "HA-xxxx/Resources/HSS_Chef_Test_7.2" (working code with resource pool)
> name = "HA-HPxxx/Resources/JCATVAPP/testvappresourcepool" #(not working resource pool under vAPP)
> datacenter_id = "${data.vsphere_datacenter.dc.id}"
> }
> data "vsphere_network" "network" {
> name = "vxw-xxxxxxxxxxxxx"
> datacenter_id = "${data.vsphere_datacenter.dc.id}"
> }
> data "vsphere_virtual_machine" "vm_template" {
> name = "rhel-68-base"
> datacenter_id = "${data.vsphere_datacenter.dc.id}"
> }
> resource "vsphere_virtual_machine" "soa" {
> name = "baluTest"
> resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
> datastore_id = "${data.vsphere_datastore.datastore.id}"
> num_cpus = 4
> memory = 16384
> guest_id = "${data.vsphere_virtual_machine.vm_template.guest_id}"
> scsi_type = "${data.vsphere_virtual_machine.vm_template.scsi_type}"
> network_interface {
> network_id = "${data.vsphere_network.network.id}"
> adapter_type = "${data.vsphere_virtual_machine.vm_template.network_interface_types[0]}"
> }
> disk {
> name ="IE-71--apsp.soa-baluTest.vmdk"
> size = "${data.vsphere_virtual_machine.vm_template.disks.0.size}"
> eagerly_scrub = "${data.vsphere_virtual_machine.vm_template.disks.0.eagerly_scrub}"
> thin_provisioned = "${data.vsphere_virtual_machine.vm_template.disks.0.thin_provisioned}"
> }
> clone {
> template_uuid = "${data.vsphere_virtual_machine.vm_template.id}"
> customize {
> linux_options {
> host_name = "apsp-soooa"
> domain = "asw.hps.local"
> }
> network_interface {
> ipv4_address = "10.3.xxxx"
> ipv4_netmask = "24"
> }
> dns_server_list = ["10.xxxxx"]
> dns_suffix_list = ["asw.hps.local"]
> ipv4_gateway = "10.3.xxxx"
> }
> }
> provisioner "remote-exec" {
> inline = [
> "hostname apsp-soa",
> "sed -i 's/HOSTNAME=.*$/HOSTNAME=apsp-soa/' /etc/sysconfig/network",
> "service NetworkManager restart",
> ]
> connection {
> type = "ssh"
> host = "10.3.x.x"
> user = "root"
> password = "XXXXXXXXXX"
> }
> }
> provisioner "file" {
> source = "/tmp/test.sh"
> destination = "/tmp/test.sh"
> connection {
> type = "ssh"
> host = "10.3.x.x"
> user = "root"
> password = "xxxx"
> }
> }
> provisioner "remote-exec" {
> inline = [
> "chmod +x /tmp/test.sh",
> "sh /tmp/test.sh",
> ]
> connection {
> type = "ssh"
> host = "10.3.x.x"
> user = "root"
> password = "xxxxx"
> }
> }
> provisioner "chef" {
> connection {
> type = "ssh"
> host = "10.3.x.x"
> user = "root"
> password = "xxxxxx"
> }
> environment = "_default"
> run_list = ["first_cookbook::default"]
> fetch_chef_certificates = "false"
> node_name = "training-user1"
> server_url = "https://10.3.x.x/organizations/chef"
> user_name = "training-user1"
> user_key = "${file("/home/bxxxx/.chef/training-user1.pem")}"
> on_failure = "fail"
> recreate_client = "true"
> ssl_verify_mode = "verify_none"
> }
> }
> 
> ################################################

**Comment by aareet** [comment] 2019-10-10 20:20
@balubalananda can you share why this was reopened? Are you able to reproduce the issue in Terraform 0.12 and the latest version of the provider release?

**Closed** 2019-11-21 17:07 UTC
Labels: bug, waiting-response
