### ISSUE TITLE
cannot find network device: invalid ID ""

### ISSUE THREAD

**Issue by johnjelinek** [terraform-providers/terraform-provider-vsphere#464] opened 2018-04-10 19:21 UTC
### Terraform Version

```
terraform -v
Terraform v0.11.3
+ provider.infoblox (unversioned)
+ provider.null v1.0.0
+ provider.vsphere v1.4.0
```

### vSphere Provider Version

```
terraform providers
.
├── provider.infoblox
├── provider.null
├── provider.vsphere
├── module.app-server
│   ├── provider.infoblox (inherited)
│   └── provider.vsphere (inherited)
└── module.postgres-server
    ├── provider.infoblox (inherited)
    └── provider.vsphere (inherited)
```
(darwin)

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
data "vsphere_datacenter" "dc" {
  name = "${var.vsphere_datacenter}"
}

data "vsphere_datastore" "datastore" {
  name = "${var.vsphere_datastore}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name = "${var.vsphere_resource_pool}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name = "${var.store_vm_vlan}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name = "${var.store_vm_template}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name = "${var.store_vm_hostname}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 4
  memory = 8192
  guest_id = "centos64Guest"
  sync_time_with_host = false

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "disk0"
    size = 40
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "${var.store_vm_hostname}"
        hw_clock_utc = true
        time_zone = "${var.store_time_zone}"
      }

      network_interface {
        ipv4_address = "${var.store_vm_ip_address}"
        ipv4_netmask = 24
      }

      ipv4_gateway = "${var.store_vm_ip_gateway}"
    }
  }
}
```

### Debug Output

```
2018-04-10T14:10:50.990-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.4.0_x4: 2018/04/10 14:10:50 [DEBUG] NetworkInterfaceRefreshOperation: Beginning refresh
2018-04-10T14:10:50.990-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.4.0_x4: 2018/04/10 14:10:50 [DEBUG] NetworkInterfaceRefreshOperation: Network devices located:
2018-04-10T14:10:50.990-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.4.0_x4: 2018/04/10 14:10:50 [DEBUG] NetworkInterfaceRefreshOperation: Current resource set fromstate: (key 0 at <new device>)
2018-04-10T14:10:50.990-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.4.0_x4: 2018/04/10 14:10:50 [DEBUG] NetworkInterfaceRefreshOperation: 0 devices over a 0 unit range
2018-04-10T14:10:50.990-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.4.0_x4: 2018/04/10 14:10:50 [DEBUG] NetworkInterfaceRefreshOperation: Looking for freshly-created resources to read in
2018-04-10T14:10:50.990-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.4.0_x4: 2018/04/10 14:10:50 [DEBUG] network_interface.0 (key 0 at <new device>): Reading state
2018-04-10T14:10:50.990-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.4.0_x4: 2018/04/10 14:10:50 [DEBUG] FindVirtualDevice: Looking for device with address
2018/04/10 14:10:50 [ERROR] root.postgres-server: eval: *terraform.EvalRefresh, err: vsphere_virtual_machine.vm: network_interface.0: cannot find network device: invalidID ""
2018/04/10 14:10:50 [ERROR] root.postgres-server: eval: *terraform.EvalSequence, err: vsphere_virtual_machine.vm: network_interface.0: cannot find network device: invalid ID ""
2018/04/10 14:10:50 [TRACE] [walkRefresh] Exiting eval tree: module.postgres-server.vsphere_virtual_machine.vm
```

### Expected Behavior

It should generate a Network ID

### Actual Behavior

```
* module.postgres-server.vsphere_virtual_machine.vm: vsphere_virtual_machine.vm: network_interface.0: cannot find network device: invalid ID ""
```

### Steps to Reproduce

1. `terraform apply`

**Comment by johnjelinek** [comment] 2018-04-10 21:54
Note: this error message ☝️  only started showing up after a failed apply with the error:
```
Error: Error applying plan:

2 error(s) occurred:

* module.postgres-server.vsphere_virtual_machine.vm: 1 error(s) occurred:

* vsphere_virtual_machine.vm: disk.0: cannot change the value of "thin_provisioned" - (old: false new: true)
* module.app-server.vsphere_virtual_machine.vm: 1 error(s) occurred:

* vsphere_virtual_machine.vm: disk.0: cannot change the value of "thin_provisioned" - (old: false new: true)
```

**Comment by johnjelinek** [comment] 2018-04-11 02:44
@vancluever: I'm trying to figure out how to clean up and start from scratch. Since `terraform destroy` results in the `cannot find network device: invalid ID ""` error, I can't seem to get a clean state. Do you think I should delete my state (and remote state) and manually delete the VMs?

**Comment by johnjelinek** [comment] 2018-04-11 02:54
downgraded to `1.3.2` of the vsphere provider and everything works fine.

**Comment by vancluever** [comment] 2018-04-11 15:12
@johnjelinek the error message you provided seems to indicate a disk type mismatch between your template's disk and configuration settings. They must match. We have an example [here](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#cloning-and-customization-example) that provides a good template for sourcing settings from the `vsphere_virtual_machine` data source.

I'm keeping this open though as we need to roll back VMs in the case we have issues in post-clone configuration.

Thanks!

**Comment by johnjelinek** [comment] 2018-04-11 16:10
@vancluever: why does it work in `1.3.x` as-is? Also -- even if there is a mismatch, I should be able to `terraform destroy` and try again, as it stands right now, I can't execute anything because all terraform commands result in `cannot find network device: invalid ID ""`.

**Comment by vancluever** [comment] 2018-04-11 16:30
@johnjelinek there has been no real changes to this code or logic since 1.1.0. Judging from the configuration that you are pasting, the only thing I can think of is some of your templates have disk settings that match the defaults of the `disk` sub-resource blocks. To be sure you are getting the correct settings all the time, make sure you source the settings from the data source.

Unfortunately your state will currently be unworkable, it will have to be manually fixed to continue, and might not work 100% as some other post-clone operations will not have ran. However, if you want to try, what you will want to do is look for something similar to the section below in your state for your `vsphere_virtual_machine` resources. Of course, `network_id` will not be populated, as that is the root cause of the issue:

```
                            "network_interface.#": "1",
                            "network_interface.0.adapter_type": "vmxnet3",
                            "network_interface.0.bandwidth_limit": "-1",
                            "network_interface.0.bandwidth_reservation": "0",
                            "network_interface.0.bandwidth_share_count": "50",
                            "network_interface.0.bandwidth_share_level": "normal",
                            "network_interface.0.device_address": "pci:0:7",
                            "network_interface.0.key": "4000",
                            "network_interface.0.mac_address": "00:50:56:ab:cc:dd",
                            "network_interface.0.network_id": "dvportgroup-12345",
                            "network_interface.0.use_static_mac": "false",
```

Back up your state, delete all `network_interface` instances for now and re-run `terraform refresh` to fix the state. The next apply should do its thing to bring everything back up to the correct configuration. Keep in mind that customization will not have run, so if you want that, you have to destroy and re-create the affected virtual machines.

**Comment by deanrs** [comment] 2018-04-11 20:56
I'm just going to leave a "me too" comment here.
seeing johnjelinek's same issue.
I've hard coded the provider version to be < 1.3.4 and am back in business.

**Comment by vancluever** [comment] 2018-04-12 00:27
@johnjelinek and @deanrs, one thing I forgot to mention, and you may be running into, is a situation detailed in the warning text [here](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#picking-a-disk-type) regarding disk type versus datastore type:

> NOTE: Not all disk types are available on some types of datastores. Attempting to set options inappropriate for a datastore that a disk is deployed to will result in a successful initial apply, but vSphere will silently correct the options, and subsequent plans will fail with an appropriate error message until the settings are corrected.

It's possible that the disk type may be getting changed in-flight, especially if they don't reside on the same datastore. The solution to this would be to ensure that the templates exist in the same datastore, or datastore type, and trying again.

Again, this code has not changed much since 1.1.0, and definitely not particularly since 1.3.3 -> 1.4.0. I have also tested the following cloning scenarios, and all are fine:

* Cloning with default settings from a template residing on a VMFS datastore to a VMFS datastore
* Cloning with a different disk size, VMFS to VMFS
* Cloning with a different disk size, VMFS to NFS
* Our acceptance tests cover NFS to VMFS
* Also tried cloning from VMFS to NFS, on 1.3.3, upgrading to 1.4.0, and then changing disk size

If any of the situations regarding unique datastore specifics on these templates or destination datastores are notable in your scenarios, please let me know.

In the meantime, this issue will focus on the rollback issues that currently exist with cloning, as there were certain scenarios (like the ones above) that were still not being rolled back properly. These are being fixed so that VMs will be deleted.

Also, can you please confirm for me if this is happening on cloning, as most of the history so far has been running under the assumption that this is the case?

Thanks!

**Comment by vancluever** [comment] 2018-04-13 17:52
Hey @johnjelinek and @deanrs, we've merged #467 which should correct the issues with post-clone configuration corrupting the resource state in a way that makes the resource unusable without manual modification. This may not necessarily fix the issue for you, but at least it will allow for better trial and error when trying to troubleshoot the configuration.

If you can open any new problems as a new issue that would be great.

Thanks!

**Closed by vancluever** 2018-04-13 17:52 UTC
Labels: bug

**Comment by gaui** [comment] 2018-04-21 04:42
Please release #467 - having the same problem.

```
vsphere_virtual_machine.vsphere_node.1: network_interface.0: cannot find network device: invalid ID ""
```

**Comment by deanrs** [comment] 2018-05-02 17:03
going to mention that i have the same issue as i've had previously.  Not an issue with vsphere provider < 1.3.4 but trying to use 1.4.1 shows the odd behavior:
```
* module.api.vsphere_virtual_machine.anastance: 1 error(s) occurred:

* vsphere_virtual_machine.anastance: error reconfiguring virtual machine: error processing disk changes post-clone: disk.0: cannot change the value of "thin_provisioned" - (old: false new: true)
```

I am using a vsphere template for building new vms and minimally describe the disk in terraform.  Our vsphere admin says the template is supposed to use thin provisioning.

```
  disk {
    label = "${var.host_dc}-${var.host_basename}${var.svc_count}-${count.index + 1}-${var.environment}.vmdk"
    size = "${lookup(var.vsphere_disk, var.instance["type"], "20")}"
  }
```
