### ISSUE TITLE
Terraform crashed after upgrade of vCenter from 6.5 to 6.7

### ISSUE THREAD

**Issue by hmalinov** [terraform-providers/terraform-provider-vsphere#602] opened 2018-08-23 16:27 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Run `terraform -v` to show the version. If you are not running the latest
version of Terraform, you can try upgrading, depending on if your problem is
with the provider or with Terraform core itself.

### vSphere Provider Version

./terraform version
Terraform v0.11.7
+ provider.google v1.4.0
+ provider.vsphere v1.6.0

### Affected Resource(s)

Terraform crashed after upgrade of vCenter from 6.5 to 6.7

### Terraform Configuration Files
No changes done on the Terraform configuration files

### Debug Output

[crash.log](https://github.com/terraform-providers/terraform-provider-vsphere/files/2317226/crash.log)

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing
the output of the `crash.log`.

### Expected Behavior

Working as usual.

### Actual Behavior

See the crash.log

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by bill-rich** [comment] 2018-09-07 00:11
The root cause of this seems to be missing LatencySensitivity which is tracked in #531. Closing to track there.

**Closed by bill-rich** 2018-09-07 00:11 UTC
Labels: bug, crash
