### ISSUE TITLE
create_before_destroy

### ISSUE THREAD

**Issue by deberon** [terraform-providers/terraform-provider-vsphere#342] opened 2018-01-09 18:19 UTC
I've been reading documentation for the best way to use create_before_destroy with this provider plugin but I haven't been able to find anything. In order to avoid naming conflicts I use a semi-unique name for each server by appending the first 5 characters of a hash of the template ID. This means the name changes whenever the template is updated. However, having just a name change means the VM is renamed instead of being destroyed/recreated. Which means I get an error that the rename process may delete the disk and that I should use [this method for parameterized disk names](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#parameterizing-virtual-machine-name-during-cloning). However when I use that method I get an error that it's an invalid disk name because it doesn't match what the server name is.

Are there any recommendations on the best way to use create_before_destroy? Thanks!

**Comment by jason-azze** [comment] 2018-01-09 18:36
@deberon This is not a direct answer to you question, #324 might be of interest.

**Comment by deberon** [comment] 2018-01-09 18:42
Thanks @jason-azze I actually found that during my research. Is the preferred method to use a manually incremented counter then? I was hoping for a solution that was a little more hands off, but if that's not possible at this point I can deal with having to update it manually.

Also, using that method do you run into problems with terraform attempting to rename your machine? Do you also have to manually taint the resource to get it to destroy/create again? Thanks for the prompt reply!

**Comment by jason-azze** [comment] 2018-01-09 18:53
I feel like a crude barbarian for using the manually incremented counter, but it works for me. :-) I've seen more sophisticated methods floating around here in others' code examples.

I ended up turning off CBD, that is, setting it to `false`, because for my use case (creating zillions of Jenkins agent machines) I  want my VMs to keep their name once I have provisioned them. So I haven't gotten to do more exploration. I don't need to do zero-downtime deployments, so I can live with destroy-before-create.

**Comment by deberon** [comment] 2018-01-10 16:47
Thanks for the insight @jason-azze! That's helpful. I'm still not clear on how to get the VM to destroy/create instead of being renamed.

**Comment by deberon** [comment] 2018-01-11 16:15
@vancluever I see you labeled this as a bug. Would it be helpful for me to provide more technical details? I was under the impression I was just doing something incorrectly.

**Comment by vancluever** [comment] 2018-01-11 16:57
Hey @deberon, it's actually labelled as a bug due to the issues @jason-azze mentioned regarding the VM being deleted first even when CBD was enabled, leading to his broken state issues, so kind of as a duplicate of #324.

However, looking at this a bit more, I think I see a few other things going on here not necessarily related to `create_before_destroy`, namely surrounding the rigid disk naming requirements that I want to work on getting rid of (documented in #295). Once this is out, a lot of what is in this issue will be moot (you will only have to worry about the VM being renamed as the plan is to no longer manage the names of the virtual disks).

So this is a bug for those reasons - I think that we are fine for extra information unless you think thre's any important details we should know about!

**Comment by deberon** [comment] 2018-01-12 19:11
Ah thanks for the clarification @vancluever. In the mean time, is there anyway I can force the virtual_machine resource to destroy instead of rename? It seems like just changing the name and source template of the resource isn't enough to trigger a destroy/create.

**Comment by jason-azze** [comment] 2018-01-12 20:52
@deberon If the source template has a new UUID, it should force a new resource. Just renaming the source template doesn't cause the UUID to change, but (for example) making a new VM from the template and converting _that_ to a template results in a fresh UUID. I learned this the hard way in #182. :-)

**Comment by vancluever** [comment] 2018-01-12 21:43
Just a note on the disk stuff - this is a stop-gap and won't be around for much longer. The work in #295 will be worked on soon so we have something for either 1.3.0 or 1.4.0. It's a priority though because it addresses problems like this.

**Comment by bill-rich** [comment] 2019-06-26 00:39
Closing as this should be addressed between the comments and #295. If I've missed something, we can either reopen the issue or create a new one with more updated information.

**Closed by bill-rich** 2019-06-26 00:39 UTC
Labels: bug
