### ISSUE TITLE
validation failed (ServerFaultCode: NoPermission)

### ISSUE THREAD

**Issue by fl64** [terraform-providers/terraform-provider-vsphere#964] opened 2020-02-04 09:11 UTC
Hi, after updating the vsphere provider to version 1.16 I get permission errors on `terraform plan\apply`

### Terraform Version

> Terraform v0.12.20

### vSphere Provider Version

>  provider.vsphere v1.16.0

### Affected Resource(s)
- `vsphere_virtual_machine`

### Debug Output

https://gist.github.com/fl64/3d32e6917ce3b82415e624e66ce239c0

### Expected Behavior

With vsphere provider v1.15 `terraform plan` is run successfully and the resources to be created are displayed.

### Actual Behavior

The terraforms connects to the sphere, but I get an errors like this:
```
Error: disk.0: validation failed (ServerFaultCode: NoPermission)

  on .terraform/modules/dnsmasq/main.tf line 69, in resource "vsphere_virtual_machine" "vm":
  69: resource "vsphere_virtual_machine" "vm" {
```

### Steps to Reproduce
 `terraform plan`

**Comment by aareet** [comment] 2020-02-04 16:56
Appears to be a duplicate of #966

**Comment by bill-rich** [comment] 2020-02-06 00:43
Thank @fl64 for filing this issue. The information was helpful in tracking down the root cause. I'm going to consolidate this with #966 and track it there.

**Closed by bill-rich** 2020-02-06 00:43 UTC
Labels: bug

**Comment by manishingole-coder** [comment] 2020-02-18 14:48
I am experiencing the same issue when I create VM. Can we please fix this issue

**Comment by aareet** [comment] 2020-02-18 15:52
@manishingole-coder are you facing the same issue with version 1.16.1?

**Comment by aareet** [comment] 2020-02-18 15:52
If so, please file a new ticket with the relevant details

**Comment by manishingole-coder** [comment] 2020-02-18 16:12
Yes, I am facing this issue with version 1.16.1. I will create a new ticket.
