### ISSUE TITLE
Attach multiple disk in loop to VM

### ISSUE THREAD

**Issue by akhilesh0** [terraform-providers/terraform-provider-vsphere#546] opened 2018-06-06 05:40 UTC
Hi

Currently we don't have feature to loop through number of disk with varying sizes required for VM. As we are using terraform to deploy whole environment which contains varying disk. We need feature something like 

resource "vsphere_virtual_machine" "vm" {
 ...
 disk {
    count = "${lenght(var.disk_name)}"
    label = "${element(var.disk_name, count.index}"
    size  = "${element(var.disk_size, count.index)}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }
  ...
}

Please let me know if some other solution is available.

Regards
Akhilesh

**Comment by michaelhajjar** [comment] 2018-06-06 12:20
need something like this too for adding extra disks where the disks can be defined in a module like this:

vm_disks = {
    disk1 {
       label = "disk1"
       size = 50
       unit_number = 1}

   disk2 {
       label = "disk2"
       size = 50
       unit_number = 2}
}

**Comment by rismoney** [comment] 2018-06-08 20:41
seems like a dupe of #415

**Comment by bill-rich** [comment] 2019-06-25 23:33
Agreed with @rismoney. Also, this is now possible with Terraform v0.12.

**Closed by bill-rich** 2019-06-25 23:33 UTC
Labels: enhancement
