### ISSUE TITLE
No MAC assignment possible 

### ISSUE THREAD

**Issue by z002Holpp** [terraform-providers/terraform-provider-vsphere#865] opened 2019-10-10 12:04 UTC
### Terraform Version
Terraform 0.12.9 and 0.12.10

### vSphere Provider Version
Terraform vSphere Provider 1.12.0 and 1.13.0

### Affected Resource(s)
vsphere_virtual_machine

### Terraform Configuration Files

```hcl
provider "vsphere" {
  user           = "${var.vsphere_user}"
  password       = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_server}"

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_virtual_machine" "template" {
  name          = "${var.windows_server_templatename}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name             = "${var.windows_server_vmname}"
  folder           = "/hcone/vm/${var.windows_vm_foldername}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 8
  memory   = 32768
  firmware = "efi"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  wait_for_guest_net_timeout=20
  wait_for_guest_net_routable="false"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
    mac_address = "00:50:56:88:08:6A"
    use_static_mac = true
  }

  disk {
      label            = "disk0"
      size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
      eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
      thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
      unit_number      = 0
    }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      windows_options {
        computer_name  = "SOMEHOSTNAME"
        workgroup      = "WORKGROUP"
      }
      network_interface {
      }
    }
  }
}
```

### Debug Output
https://gist.github.com/z002Holpp/e287ad7d6b55f90cdeb4eb50c53f1903

### Panic Output

n.a.

### Expected Behavior

I have a Windows Server 2016 System as template in VMware. With Terraform, the following actions shall be performed:
1)	a VM shall be instantiated from the template
2)	the hostname shall be set
3)	a MAC address shall be assigned to the network adapter 
Since the system uses DHCP, the IP address is automatically resolved by the MAC address given.

### Actual Behavior

When terraform is executed, the following happens:
•	VM is instantiated correctly
•	the hostname is set correctly
•	the MAC address is NOT assigned
The lack of a MAC leads to no IP address is assigned (still has a default IP) and this makes “Terraform apply” to time-out.

### Steps to Reproduce
terraform apply

### Important Factoids

Interestingly, when the machine is up for a while and I login (“terraform apply” is still running and waiting for an IP), and I set the MAC manually, immediately the IP is assigned by DHCP and terraform returns successfully. 
This proves that the only obstacle in my scenario is that terraform for some reason is not able to assign the MAC address!

### References
n.a.

**Comment by aareet** [comment] 2019-10-10 20:24
@z002Holpp this looks like a duplicate of #488. I'll close this in favour of that earlier report, but please reopen if I've got it wrong.

**Closed by aareet** 2019-10-10 20:24 UTC

**Comment by z002Holpp** [comment] 2019-10-11 05:45
Hi aaret,

for me it does not look like a duplicate. 
At least, in your referenced issue, I dont really understand the workarund proposal. Could this be once explained in detail?

> problem is only observed when using linked clone mode
Linked clone mode refers to hard disks, right? What exactly could this affect MAC address assignment in the network adapter?

> problem resolved for me by removing all network adapters from snapshot of machine template; then static mac address is set properly
If all network adapters are removed from the template, then the instantiated VM does also not have a network adapter, correct? Then how can a MAC address be assigned?

Thanks in advance!

**Comment by z002Holpp** [comment] 2019-10-11 06:43
Hi,

just tried it once and it actually works like that:

1) remove the network adapter from the template

2) Change the tf file in the following way such that apater type is assigned hard-coded:

```tf
  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "e1000e"
    mac_address = "00:50:56:88:08:6A"
    use_static_mac = true
  }
```
Then during instantiation of the VM a new network adapter of that type is instantiated.
You can close the issue.
