### ISSUE TITLE
Error fetching datacenter: datacenter 'dc' not found

### ISSUE THREAD

**Issue by freakssy** [terraform-providers/terraform-provider-vsphere#774] opened 2019-05-29 15:03 UTC
Hi,

### Terraform Version
± terraform -v
Terraform v0.12.0
+ provider.vsphere v1.11.0

### vSphere Provider Version

± terraform providers
.├── module.virtual-machine
   └── provider.vsphere ~>1.11

### Vcenter Version

Informations de version

Version
    6.7.0 
Build
    13639324 

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

data "vsphere_datacenter" "datacenter" {
  name = "${var.datacenter}"
}
....

variable "datacenter" {
  type        = "string"
  description = "The datacenter to deploy the virtual machines to."
}

module "virtual-machine" {
  source               = "git@gitlab**********.git?ref=admin1n"
  datacenter           = "dc"
....
}

### Panic Output

Error: error fetching datacenter: datacenter 'dc' not found

  on .terraform/modules/virtual-machine/data_sources.tf line 1, in data "vsphere_datacenter" "datacenter":
   1: data "vsphere_datacenter" "datacenter" {

### Expected Behavior

It should find the datacenter name

### Actual Behavior

datacenter name not found

### Steps to Reproduce

1.terraform init
2.terraform plan

However, I can find datacenter with govc:

# ./govm datacenter.info
Name:                dc
  Path:              /dc
  Hosts:             3
  Clusters:          2
  Virtual Machines:  46
  Networks:          9
  Datastores:        7

Thanks for help

**Comment by bill-rich** [comment] 2019-05-31 16:13
Hi @freakssy! Thanks for reporting this issue. In looking into reproducing the issue, I noticed the virtual-machine module does not seem to be Terraform v0.12 compatible, so I will be working on getting that updated soon.

From the configs you have posted, I don't see any reason why your datacenter is not being found. To help in troubleshooting, can you please try a minimal configuration with just a datacenter data source and setting `TF_LOG=DEBUG`? If that is able to find the datacenter without issue, then we'll need to take a closer look at your module to see if there is a difference there. To continue down that path, a DEBUG log and the content of the module will be helpful.

**Comment by bill-rich** [comment] 2019-06-14 20:53
Closing since there hasn't been a response in a while.

**Closed by bill-rich** 2019-06-14 20:53 UTC
Labels: question, waiting-response
