### ISSUE TITLE
terraform.EvalValidateResource Errors: [connection is shut down]

### ISSUE THREAD

**Issue by Koleon** [terraform-providers/terraform-provider-vsphere#456] opened 2018-04-06 14:19 UTC
Hello there,
I deploy different linux distros and Windows machines from VMware templates. In total about 25 machines. Unfortunately the main.tf is pretty complex and I cannot simulate the panic situation via smaller main.tf (it just do not fail at all). 
### Terraform Version
```
Terraform v0.11.5
+ provider.vsphere v1.3.3
```

### Terraform Configuration Files

```hcl
```

### Crash Output
https://gist.github.com/Koleon/82bbbea2d787799397ea116bef7e8ea6

### Expected Behavior

All VMs are deployed without any error.

### Actual Behavior

A few of VMs are deployed some of them are not.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Additional Context

* The [timeout](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#timeout) was changed to 40 minutes and [wait_for_guest_net_timeout](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#wait_for_guest_net_timeout) to 10 minutes.
* VMware vSphere 6.5

### References

- #73 (Might be)

**Comment by vancluever** [comment] 2018-04-10 15:16
@Koleon we can add a nil check for the crash, but we would issue an error in that case anyway, and without an easy way to reproduce the situation, I'm not 100% inclined to as we usually like to add tests for things. I understand it's large, but do you mind sharing your config?

The line you quoted is a situation that does not seem to come up during normal testing operations (`DVSManagerLookupDvPortGroup` returns errors when it can't find a port group or encounters another error), and we test on Ubuntu 16.04 as well.

Thanks!

**Comment by Koleon** [comment] 2018-04-11 08:34
@vancluever thanks for your reply and effort to help out. Just to be sure, I installed new ubuntu 16.04 and run terraform v0.11.7 once again, unfortunately it failed. So please see attachment - [terraform-cycz.tar.gz](https://github.com/terraform-providers/terraform-provider-vsphere/files/1897918/terraform-cycz.tar.gz)

We have 2 workspaces - default, bt1, lately there might be bt2. Terraform files are divided into 2 groups. Files related to bt{1-2} start with **wks_bt_*{dmz, srv, ops, usr}*.tf** and **wks_default_*{global, main}*.tf** related to defaut workspace. Most of the rest files are self-explaining hopefully. The crash happens only during bt1 deploy. 
Thank you for cooperation!

**Comment by vancluever** [comment] 2018-04-12 18:12
Hey @Koleon, there is a fix now for this in https://github.com/terraform-providers/terraform-provider-vsphere/pull/471. If you have the ability to do so, would you please try your issue again with a [custom built provider binary](https://github.com/terraform-providers/terraform-provider-vsphere#building-the-provider) against the branch in the PR to see that resolves the issue for you? This can help us confirm that the issue will be fixed in the next release.

If you still run into the error (there's a good chance you will, but this time without a crash) the new error message should tell you the failing DVS UUID and portgroup. If you get valid values for these, can you try looking them up using the DVSManagerLookupDvPortGroup function in the MOB? The URL for the MO would be https://yourvcenterserver.local/mob/?moid=DVSManager (where `yourvcenterserver.local` is your vCenter server). PS: More info in the MOB [here](https://www.terraform.io/docs/providers/vsphere/index.html#via-the-vsphere-managed-object-browser-mob-).

Thanks!

**Comment by vancluever** [comment] 2018-04-13 17:29
Hey @Koleon, this fix is now in master. I'm going to close this now, but if you have a chance can you give it a go, and open a new issue with the results, as it should no longer crash, and if it does it will probably be due to another issue?

Thanks!

**Closed by vancluever** 2018-04-13 17:29 UTC
Labels: bug, crash
