### ISSUE TITLE
Error: disk.0: virtual machine with UUID "" not found (1.16)

### ISSUE THREAD

**Issue by mitchellmaler** [terraform-providers/terraform-provider-vsphere#968] opened 2020-02-04 19:17 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Terraform v0.12.20

### vSphere Provider Version

provider.vsphere v1.16.0

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`
- `vsphere_distributed_port_group`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "vm" {
  depends_on       = [tls_private_key.vm_terraform_ssh_key]
  name             = var.vsphere_vm_name
  resource_pool_id = var.vsphere_resource_pool_id
  datastore_id     = var.vsphere_datastore.id
  folder           = var.vsphere_vm_folder_path

  num_cpus = var.vsphere_virtual_machine_cpu_count
  memory   = var.vsphere_virtual_machine_memory_mb
  guest_id = var.vsphere_vm_template.guest_id

  scsi_type = var.vsphere_vm_template.scsi_type

  network_interface {
    network_id   = var.vsphere_network.id
    adapter_type = var.vsphere_vm_template.network_interface_types[0]
  }

  disk {
    label            = "disk0"
    size             = var.vsphere_vm_template.disks.0.size + var.vsphere_virtual_machine_srv_extend_size
    eagerly_scrub    = var.vsphere_vm_template.disks.0.eagerly_scrub
    thin_provisioned = var.vsphere_vm_template.disks.0.thin_provisioned
  }

  extra_config = {
    "guestinfo.userdata" = base64gzip(
      templatefile("${path.module}/templates/userdata.yml", {
        vm_hostname            = var.vsphere_vm_name,
        vm_domain              = var.vsphere_vm_domain,
        vm_rancher_ssh_pub_key = tls_private_key.vm_terraform_ssh_key.public_key_openssh
    }))
    "guestinfo.userdata.encoding" = "gzip+base64"
  }

  clone {
    template_uuid = var.vsphere_vm_template.id
  }
}
```

### Debug Output

https://gist.github.com/mitchellmaler/cd290f3c33bd7d1723e661e1c37a7bbf

### Expected Behavior

What should have happened?

Not error about a VM not existing. The UUID is not the vm but a cloned template UUID. If the cloned template doesn't exist anymore then it shouldn't try to refresh state against that disk. Really it should refresh against the actual VM it creates not against the template.

### Actual Behavior

What actually happened?

Errors saying it cannot find the UUID of VM the disk was created from.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

### Important Factoids

The cloned template along with the disk are managed outside my control. They are updated/replaced which means the template UUID will not always exists. If I downgrade the provider to 1.15 I do not get this error anymore. Maybe the disk refresh should only occur if the template refresh passes.

**Comment by aareet** [comment] 2020-02-04 19:35
Duplicate of #967

**Comment by bill-rich** [comment] 2020-02-06 21:28
This should be fixed now with v1.16.1. Please let me know if you're still experiencing the issue.

**Closed by bill-rich** 2020-02-06 21:28 UTC
Labels: bug

**Comment by Rodrigo0461** [comment] 2020-02-07 13:23
Hi
Now I get this error (With v1.16.1)

`ServerFaultCode: NoPermission: RESOURCE (vm-8908), ACTION (queryAssociatedProfile): RESOURCE (vm-8908), ACTION (PolicyIDByVirtualMachine)
`

Any idea ?

**Comment by kbcz1989** [comment] 2020-02-08 09:55
v1.16.1 works ok for me now.

**Comment by Koleon** [comment] 2020-02-26 07:51
> Hi
> Now I get this error (With v1.16.1)
> 
> `ServerFaultCode: NoPermission: RESOURCE (vm-8908), ACTION (queryAssociatedProfile): RESOURCE (vm-8908), ACTION (PolicyIDByVirtualMachine) `
> 
> Any idea ?

Hi, look at [this reply](https://github.com/terraform-providers/terraform-provider-vsphere/issues/974#issuecomment-588435697). Unfortunately I don't know where to set the `Profile-driven` permission, in other words on what object??

**Comment by victorbiga** [comment] 2020-04-07 11:30
had the same error, the issue was on vcenter side, more permissions required, don't know which one exactly but it was related to datastore management. Terraform was deleting the resource because it was unable to provision the data disk, nothing to do with terraform syntax or version
