### ISSUE TITLE
cannot locate virtual machine or template with UUID

### ISSUE THREAD

**Issue by johnjelinek** [terraform-providers/terraform-provider-vsphere#376] opened 2018-01-28 19:11 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version

```
Terraform v0.11.2
+ provider.vsphere v1.3.0
```

### vSphere Provider Version

`1.3.0_x4`

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
data "vsphere_virtual_machine" "template" {
  name = "${var.vm_template}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
...
  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
...
  }
```

### Expected Behavior

It should've found the template, `govc` (v. 0.16.1) can find the template:
```
$ govc vm.info db

Name:           db
  Path:         /DC ONE/vm/packer-templates/db
  UUID:         420a16a5-dd7b-8507-b853-159c679ee137
  Guest name:   CentOS 4/5/6 (64-bit)
  Memory:       1024MB
  CPU:          1 vCPU(s)
  Power state:  poweredOff
  Boot time:    <nil>
  IP address:
  Host:         dc.example.com
```

### Actual Behavior

```
Error: Error running plan: 2 error(s) occurred:

2018/01/28 12:43:32 [DEBUG] plugin: waiting for all plugin processes to complete...
* module.db-server.vsphere_virtual_machine.vm: 1 error(s) occurred:

* module.db-server.vsphere_virtual_machine.vm: cannot locate virtual machine or template with UUID "420a16a5-dd7b-8507-b853-159c679ee137": virtual machine with UUID "420a16a5-dd7b-8507-b853-159c679ee137" not found
```

It seems like it should've found it considering it grabbed the correct UUID.

### Steps to Reproduce

1. `terraform plan`

**Comment by johnjelinek** [comment] 2018-01-28 19:27
oh -- I guess I can reproduce this in `govc`:
```
govc vm.info -vm.uuid=420a16a5-dd7b-8507-b853-159c679ee137
govc: no such VM
2018/01/28 19:27:07.030115 [ERR] (cli) unexpected exit from subprocess (1)
```

**Comment by johnjelinek** [comment] 2018-01-28 19:31
Opened this for `govc`: https://github.com/vmware/govmomi/issues/1020

**Comment by den-is** [comment] 2018-01-29 06:54
same here :(
and probably people here https://github.com/terraform-providers/terraform-provider-vsphere/issues/271 have same issue

**Comment by vancluever** [comment] 2018-01-29 16:57
Hey all, as this is a duplicate of #271, I'm closing this issue. You can follow the progress over there.

Thanks!

**Closed by vancluever** 2018-01-29 16:57 UTC
