### ISSUE TITLE
multiple virtual machines withUUID found

### ISSUE THREAD

**Issue by johnjelinek** [terraform-providers/terraform-provider-vsphere#382] opened 2018-02-02 20:43 UTC
### Terraform Version & vSphere Provider Version

```
Terraform v0.11.3
+ provider.vsphere (1.3.1)
```

### Debug Output

```
2018-02-02T14:23:41.957-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:23:41 [DEBUG] Locating virtual machine with UUID "420ae87a-bce6-2e1b-f6f6-fc813272ba24"
2018-02-02T14:23:41.957-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:23:41 [DEBUG] Using ContainerView to look up UUID "420ae87a-bce6-2e1b-f6f6-fc813272ba24"
2018/02/02 14:23:42 [ERROR] root.app-server: eval: *terraform.EvalDiff, err: cannot locate virtual machine or template with UUID "420ae87a-bce6-2e1b-f6f6-fc813272ba24": multiple virtual machines with UUID"420ae87a-bce6-2e1b-f6f6-fc813272ba24" found
2018/02/02 14:23:42 [ERROR] root.app-server: eval: *terraform.EvalSequence, err: cannot locate virtual machine or template with UUID "420ae87a-bce6-2e1b-f6f6-fc813272ba24": multiple virtual machines with UUID "420ae87a-bce6-2e1b-f6f6-fc813272ba24" found
2018/02/02 14:23:42 [ERROR] root.postgres-server: eval: *terraform.EvalDiff, err: cannot locate virtual machine or template with UUID "420a8fb9-1dcb-7849-514b-e1895928ae89": multiple virtual machines withUUID "420a8fb9-1dcb-7849-514b-e1895928ae89" found
```

### Expected Behavior

It should've found the template by UUID

### Actual Behavior

It found multiple templates (and the other ones didn't match the UUID)

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This filter is "finding" more than one instance:
https://github.com/terraform-providers/terraform-provider-vsphere/blob/21985b8fd66ebdb1b2927acd7ff4e7f5cd3b9a67/vsphere/internal/helper/virtualmachine/virtual_machine_helper.go#L131

Here's a conversation about this [upstream](https://github.com/vmware/govmomi/issues/1020#issuecomment-362693459). Essentially, this `govc` command finds multiples (I think erroneously):
```
govc find / -type m -config.uuid "420ae87a-bce6-2e1b-f6f6-fc813272ba24"
```
but this `govc` command finds exactly what I want:
```
govc find / -type m -config.instanceUuid 420ae87a-bce6-2e1b-f6f6-fc813272ba24
```

### References

- https://github.com/vmware/govmomi/issues/1020
- https://github.com/terraform-providers/terraform-provider-vsphere/pull/377

**Comment by vancluever** [comment] 2018-02-02 20:56
Hey @johnjelinek, this is something that I am actually tracking in #282, so the plan is to eventually migrate to instance UUID. There are also details in there on when a UUID might be duplicated.

How was this template generated? Was it generated from a clone in vSphere or via some sort of other process? Can you try cloning the VM again and see if get a different UUID? If so, this can be the workaround for now. Another workaround would be to generate a new UUID, edit the .vmx file, and update the UUID there.

**Comment by johnjelinek** [comment] 2018-02-02 21:06
@vancluever: The template was generated with Packer from an ISO and then I use `govc ova.import` to ship it to a vSphere host. It does get a different UUID if I ship it again. But even after that, multiple entires show up again (but it's a different set of multiple entries).

**Comment by johnjelinek** [comment] 2018-02-02 21:11
I changed the filter to `config.instanceUuid` and I get more details:
```
2018-02-02T14:58:04.914-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:04 [DEBUG] DiskDiffOperation: Beginning disk diff customization
2018-02-02T14:58:04.914-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:04 [DEBUG] ValidateVirtualMachineClone: Validating fitness of source VM/template 420a8fb9-1dcb-7849-514b-e1895928ae89
2018-02-02T14:58:04.914-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:04 [DEBUG] Locating virtual machine with UUID "420a8fb9-1dcb-7849-514b-e1895928ae89"
2018-02-02T14:58:04.914-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:04 [DEBUG] DiskDiffOperation: Beginning collective diff validation (indexes aligned to new config)
2018-02-02T14:58:04.914-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:04 [DEBUG] diskLabelOrName: label: "disk0" name: ""
2018-02-02T14:58:04.914-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:04 [DEBUG] Using ContainerView to look up UUID "420a8fb9-1dcb-7849-514b-e1895928ae89"
2018-02-02T14:58:04.914-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:04 [DEBUG] diskLabelOrName: Using defined label value "disk0"
2018-02-02T14:58:04.914-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:04 [DEBUG] DiskDiffOperation: Beginning diff validation and normalization (indexes aligned to old state)
2018-02-02T14:58:04.914-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:04 [DEBUG] DiskDiffOperation: New resource set post-normalization: (key 0 at <new device>)
2018-02-02T14:58:04.914-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:04 [DEBUG] DiskDiffOperation: Disk diff customization complete, sending new diff
2018-02-02T14:58:04.915-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:04 [DEBUG] ValidateVirtualMachineClone: Validating fitness of source VM/template 420ae87a-bce6-2e1b-f6f6-fc813272ba24
2018-02-02T14:58:04.915-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:04 [DEBUG] Locating virtual machine with UUID "420ae87a-bce6-2e1b-f6f6-fc813272ba24"
2018-02-02T14:58:04.915-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:04 [DEBUG] Using ContainerView to look up UUID "420ae87a-bce6-2e1b-f6f6-fc813272ba24"
2018-02-02T14:58:06.007-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:06 [DEBUG] VM "/DC0/vm/Discovered virtual machine/avm" found for UUID "420a8fb9-1dcb-7849-514b-e1895928ae89"
2018-02-02T14:58:06.007-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:06 [DEBUG] Fetching properties for VM "/DC0/vm/Discovered virtual machine/avm"
2018-02-02T14:58:06.008-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:06 [DEBUG] VM "/DC0/vm/Discovered virtual machine/avm" found for UUID "420ae87a-bce6-2e1b-f6f6-fc813272ba24"
2018-02-02T14:58:06.008-0600 [DEBUG] plugin.terraform-provider-vsphere: 2018/02/02 14:58:06 [DEBUG] Fetching properties for VM "/DC0/vm/Discovered virtual machine/avm"
```

it's real strange that it mentions that it's specifically searching for a uuid that isn't associated with the template I'm referencing:
`wrong`
```
[DEBUG] Using ContainerView to look up UUID "420a8fb9-1dcb-7849-514b-e1895928ae89"
```
`right`
```
[DEBUG] Locating virtual machine with UUID "420ae87a-bce6-2e1b-f6f6-fc813272ba24"
```

**Comment by Chris-Carmichael** [comment] 2018-02-03 17:18
I'm having the same problem.  I've dumped out every VM + UUID and verified only one exists:

```
[27]: $foo = Get-VMUUIDReport -Datacenter 'ALLENTX'
[28]: $foo | ? { $_.uuid -eq "4222c8f9-3f70-98ec-e30a-ca26dc7aede3" }

Hostname             UUID
--------             ----
packer_2016_template 4222c8f9-3f70-98ec-e30a-ca26dc7aede3
```

But the 1.3.1 provider errors out like so:

```
* vsphere_virtual_machine.vm: cannot locate virtual machine or template with UUID "42222f3f-f8e5-4ece-66bd-da5c00116f1e": multiple virtual machines with UUID "42222f3f-f8e5-4ece-66bd-da5c00116f1e" found
```

I'm forcing the provider to 1.3.0 until this is resolved.

**Comment by nhi-vanye** [comment] 2018-02-04 15:15
+1

Took the same approach as Chis and forced 1.3.0

**Comment by vancluever** [comment] 2018-02-05 05:48
Hey all, I'll be looking at this tomorrow. Sorry for the issues this has caused.

The note in tag change is mostly acknowledgement that from reports, this seemed to be working in 1.3.0 (albeit perhaps in lesser capacity), but is now completely broken in 1.3.1.

More info tomorrow.

Thanks!

**Comment by den-is** [comment] 2018-02-06 08:51
just FYI +1
have same issue when trying to create multiple machines with `count` loop
my vm template is manually created from virtual machine in vsphere 5.5

**Comment by vancluever** [comment] 2018-02-06 16:19
Hey all,

For anyone having this issue (I'm still trying to track it down), can you do the following for me:

* Run `govc find / -type m -config.uuid "UUID_GOES_HERE"`, and locate the virtual machines that match.
* From there, using the MOB (instructions on how to use the MOB [here](https://code.vmware.com/doc/preview?id=4205#/doc/PG_Appx_Using_MOB.21.2.html#994699)), locate the virtual machines, and tell me what the `uuid` attribute of the `config` attribute of each VM's MO is.

Based on the discussion here and vmware/govmomi#1020, I'm suspecting something is up with the search and UUIDs are not necessarily duplicated. As I'm still actively trying to reproduce it though, it's hard to tell.

Thanks!

**Comment by johnjelinek** [comment] 2018-02-06 17:00
```
$ govc find / -type m -config.uuid "420a8fb9-1dcb-7849-514b-e1895928ae89"

/DC0/vm/packer-templates/SCHdb
/DC0/vm/Discovered virtual machine/avm
```

![cloudapp annotation 2018-02-06 at 10 56 55 am png](https://user-images.githubusercontent.com/873610/35872443-76ef90ba-0b2c-11e8-874c-2ff2b9630a1f.png)

```
$ govc find / -type m -config.uuid "420ae87a-bce6-2e1b-f6f6-fc813272ba24"

/DC0/vm/packer-templates/SCHas
/DC0/vm/Discovered virtual machine/avm
```

![cloudapp annotation 2018-02-06 at 10 50 56 am png](https://user-images.githubusercontent.com/873610/35872408-5fa5fe30-0b2c-11e8-85ed-f5b8be26d8e7.png)


```
govc vm.info avm
Name:           avm
  Path:         /DC0/vm/Discovered virtual machine/avm
  UUID:
  Guest name:
  Memory:       0MB
  CPU:          0 vCPU(s)
  Power state:  poweredOff
  Boot time:    <nil>
  IP address:
  Host:         avm.example.com
Name:           avm
  Path:         /DC0/vm/avm
  UUID:         420a3f92-c904-04cf-38d1-b1bf886ab491
  Guest name:   Red Hat Enterprise Linux 5 (32-bit)
  Memory:       6144MB
  CPU:          2 vCPU(s)
  Power state:  poweredOn
  Boot time:    2017-01-03 21:16:45.323937 +0000 UTC
  IP address:   172.16.35.5
  Host:         avm.example.com
```

```
govc find / -type m -config.uuid "420a3f92-c904-04cf-38d1-b1bf886ab491"
/DC0/vm/avm
/DC0/vm/Discovered virtual machine/avm
```

![cloudapp annotation 2018-02-06 at 10 58 41 am png](https://user-images.githubusercontent.com/873610/35872538-b6c887d2-0b2c-11e8-8dd0-1967c393b8e4.png)

**Comment by johnjelinek** [comment] 2018-02-06 17:05
It looks like the `/DC0/vm/Discovered virtual machine/avm` that shows up in all of those is an orphaned VM.

**Comment by vancluever** [comment] 2018-02-06 17:08
@johnjelinek:

The orphaned VM is a side effect of Packer and the fact that the `vmware-iso` builder is not using API, but rather SSH, "manual" generation of the VMX file, and esxcli (this is why I was trying to reproduce this using Packer).

But the strange part to me is that the MOB says they have different UUIDs, but the inventory finder in `govc` doesn't differentiate.

I'm going to change the logic on our side so it doesn't use `RetrieveFilter` and will put in a PR shortly. Do you have the ability to try this off of master?

**Comment by vancluever** [comment] 2018-02-06 17:10
One thing - does `/DC0/vm/Discovered virtual machine/avm` show up in the MOB? If it does, what UUID does it have?

**Comment by johnjelinek** [comment] 2018-02-06 17:17
ya, I can try this off of master. Also, I haven't yet found `/DC0/vm/Discovered virtual machine/avm` in the MOB. Also, this particular orphaned VM was not created by packer.

**Comment by johnjelinek** [comment] 2018-02-06 17:22
Found it:
![cloudapp annotation 2018-02-06 at 11 21 54 am png](https://user-images.githubusercontent.com/873610/35873668-fb8fbcfc-0b2f-11e8-812f-5865cfd14795.png)

**Comment by vancluever** [comment] 2018-02-06 17:40
OK, that is interesting for sure and something I think we need to account for full stop in the update. I think it's useful for govmomi in general too as if the entire `config` data object is missing, then it sounds like `RetrieveFilter` has a false positive issue with missing keys.

Will work on the fix here shortly.

**Comment by den-is** [comment] 2018-02-06 17:46
```
vsphere_virtual_machine.vm[0]: Creation complete after 8m0s (ID: 422fd43c-b005-977d-1126-d705519adf41)
Error: Error applying plan:
1 error(s) occurred:
* vsphere_virtual_machine.vm[1]: 1 error(s) occurred:
* vsphere_virtual_machine.vm.1: cannot locate virtual machine or template with UUID "422f44a7-008d-58c4-83b5-ede9f4b89265": multiple virtual machines with UUID "422f44a7-008d-58c4-83b5-ede9f4b89265" found
```

But I can't find two instances of same `UUID`
```
govc find / -type m -config.uuid "422f44a7-008d-58c4-83b5-ede9f4b89265"
/mojo/vm/template-centos-7.4
```

there is only one template shown above with such template
confused :/

**Comment by Chris-Carmichael** [comment] 2018-02-06 22:22
Hey guys, sorry I was short on time as usual and didn't give an exhaustive methodology on how I verified there weren't duplicate SIDs.

I dumped out the entire datacenter's VMs + UUIDs and searched for the "offending" UUID in the Terraform error.  It's definitely not a dupe.  Here is some PowerCLI code for those interested.  It's very quick and dirty, so don't judge.  😁 

```
function Get-VMUUIDReport {

    <#

    .SYNOPSIS
    This function grabs the UUIDs of every machine in a cluster or the entire datacenter.

    .DESCRIPTION
    This function grabs the UUIDs of every machine in a cluster or the entire datacenter.  It was written to help us troubleshoot Terraform issues.

    .PARAMETER ClusterName
    Use this if you want to only pull the VM + UUID info for a particular cluster.

    .PARAMETER Datacenter
    Use this if you want to only pull the VM + UUID info for an entire datacenter.

    .EXAMPLE
    $DatacenterReport = Get-VMUUIDReport -Datacenter 'ALLENTX'
    $DatacenterReport | ? { $_.uuid -eq "4222c8f9-3f70-98ec-e30a-ca26dc7aede3" }

    Get all VM + UUID for the Allen Datacenter and search for a UUID.

    .EXAMPLE
    $ClusterReport = Get-VMUUIDReport -ClusterName Shared-Internal
    $ClusterReport | ? { $_.uuid -eq "42222f3f-f8e5-4ece-66bd-da5c00116f1e" }

    Get all VM + UUID for the Shared-Internal cluster and search for a UUID.

    .NOTES
    Author: Chris Carmichael
    Date:  2/3/2018

    Written to troubleshoot this error:
    * vsphere_virtual_machine.tx1labinfcentos2: cannot locate virtual machine or template with UUID "42222f3f-f8e5-4ece-66bd-da5c00116f1e": multiple virtual machines with UUID "42222f3f-f8e5-4ece-66bd-da5c00116f1e" found

    #>
    
    param (
        [Parameter(Mandatory=$false)]
        $ClusterName,
        [Parameter(Mandatory=$false)]
        [ValidateSet('ALLENTX','LISLE')]
        $Datacenter
    )

    if ($ClusterName) {

        Get-Cluster $ClusterName | Get-VM | % {
        
            $obj = "" | Select-Object Hostname,UUID
            $obj.Hostname = $_.name
            $obj.UUID = (Get-View $_.Id).config.uuid
            $obj

        }
    } elseif ($Datacenter) {

        Get-Datacenter $Datacenter | Get-VM | % {
        
            $obj = "" | Select-Object Hostname,UUID
            $obj.Hostname = $_.name
            $obj.UUID = (Get-View $_.Id).config.uuid
            $obj

        }
    }
}
```

**Comment by vancluever** [comment] 2018-02-06 23:01
Thanks @Chris-Carmichael!

I think we are getting close to a fix here - if you want to try #391 it's already been verified as fixing it for @johnjelinek, I'm just waiting on verification of the latest commit that should speed up the search a lot. :slightly_smiling_face:

**Comment by vancluever** [comment] 2018-02-07 01:42
Everyone, 1.3.2 will be out shortly with a fix for this. If everyone having this issue can test against the new version and let me know if it solves your issues, that would be great!

**Comment by den-is** [comment] 2018-02-07 07:55
awesome!!1 works now! thanks for the great job

only, optional, thing left to do is to fix provisioning of multiple dns_suffixes https://github.com/terraform-providers/terraform-provider-vsphere/issues/384 (centos74 in my case) and I will never look in this repo again :P

**Comment by vancluever** [comment] 2018-02-09 00:36
Hey all, there hasn't been any activity on this, and with 1.3.2 out, this should be fixed. As such I'm closing this issue. Thanks!

**Closed by vancluever** 2018-02-09 00:36 UTC
Labels: regression
