### ISSUE TITLE
timeout waiting for routeable interface on v0.3.0+

### ISSUE THREAD

**Issue by y0ssar1an** [terraform-providers/terraform-provider-vsphere#231] opened 2017-11-01 18:45 UTC
### Terraform Version

`v0.10.8`

### vSphere Provider Version

`provider.vsphere 0.2.2` (works)
`provider.vsphere 0.3.0` (first version that fails)
`provider.vsphere 0.4.2` (also fails)

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
provider "vsphere" {
  user                 = ""
  password             = ""
  vsphere_server       = ""
  allow_unverified_ssl = true
  version              = "0.4.2"
}

resource "vsphere_virtual_machine" "myvm" {
  name = "vm-deleteme"

  datacenter = "DC99"
  cluster    = "myclusters"

  vcpu   = "1"
  memory = "4096"

  dns_servers = ["8.8.8.8"]

  network_interface {
    label = "VM Network"
  }

  disk {
    template  = "template-20171005.1-UbuntuTrusty-DS-10-SAS-1"
    datastore = "DS-10-SAS-1"
    type      = "thin"
  }
}
```

### Debug Output

https://gist.github.com/y0ssar1an/7c27bb3ada41d1d90814254b413a0c36

```
$ ps -ef | grep terraform | grep -v grep
  501 18150 16865   0 11:16AM ttys004    0:00.51 terraform apply plan
  501 18151 18150   0 11:16AM ttys004    0:00.19 /usr/local/Cellar/terraform/0.10.8/bin/terraform apply plan
  501 18152 18151   0 11:16AM ttys004    0:00.67 /Users/ryan/clusters/vsphere2/.terraform/plugins/darwin_amd64/terraform-provider-vsphere_v0.4.2_x4
```

Everything looks fine in vCenter.

![failed_apply](https://user-images.githubusercontent.com/1250684/32291265-c9ebdf8c-bef9-11e7-96ea-c4f9f6948166.png)

### Expected Behavior

The VM should create successfully and `terraform` should return exit code 0.

### Actual Behavior

1) `timeout waiting for routeable interface`.
2) `terraform` returns exit code 1

### Steps to Reproduce

1. `terraform plan -out plan`
2. `terraform apply plan`

### Important Factoids

AFAIK there's nothing unique about our vSphere configuration. We're using Ubuntu 14.04.

**Comment by s-ramirez** [comment] 2017-11-02 19:51
I'm also seeing this error. It happens exclusively when using Ubuntu 14.04. I've tested 16.04, RHEL 7.4 and 6.9 and does seemed to work fine.

**Comment by rbmateescu** [comment] 2017-11-06 23:01
found this: https://github.com/terraform-providers/terraform-provider-vsphere/blob/eb9a0ad0a0f80048cd3adc407c6e18e8f4d01f56/CHANGELOG.md#030-september-14-2017

**Comment by surajsub** [comment] 2017-11-07 14:39
Using the provider version of 0.4.0 does not work with suse12sp2 . The default route does not get set on the vm . Adding the wait_for_guest_net = false completes the provisioning but really serves no purpose.

**Comment by vancluever** [comment] 2017-11-07 15:18
Hey all, sorry for the delay in responding to this.

First off, `wait_for_guest_net` in its current incarnation waits for, as mentioned above, a _routeable_ IP address. This broad approach is necessary because some machines (namely Windows) will report an auto-configuration address to the waiter before reporting the correct address. Further to this, we want the IP address reported to the provisioner to be as reachable as possible.

If this behaviour is not functional for your needs, or is not functioning correctly, you can indeed turn it off using `wait_for_guest_net = false`. If you do this, however, the waiter exits immediately,  more than likely before VMware tools reports a correct IP address. In this case, if you want to connect to the machine with TF after deployment, you will need to add the IP address you want to connect to in a [connection block](https://www.terraform.io/docs/provisioners/connection.html) in the provisioner. @s-ramirez, this will indeed the correct fix for your issues.

@surajsub, if customization is having problems adding the default route, it more than likely is a problem with VMware Tools' customization features and not Terraform itself. I would encourage you to check the customization log, which can usually be found at /var/log/vmware-imc/toolsDeployPkg.txt, for more details.

@s-ramirez, I'm actually curious to hear that you are having issues with Ubuntu - does the VM have VMware tools installed and correctly reporting IP addresses in the console?

**Comment by surajsub** [comment] 2017-11-07 16:02
@vancluever  - Let me check that - thanks

**Comment by y0ssar1an** [comment] 2017-11-07 19:26
In my testing, I could see in vCenter that the VMs were getting IP addresses. I confirmed they were reachable by `ssh`-ing into the boxes. But `terraform` was still waiting for a routeable IP address and eventually timed out. There may be a bug in the wait code.

**Comment by lynic** [comment] 2017-11-14 03:59
I can confirmed this in 0.4.2 and vsphere 6.5. VM get the IP and shows on vcenter ui but terraform didn't see it.

**Comment by lynic** [comment] 2017-11-14 06:59
I confirm that 0.2.2 works.

**Comment by vancluever** [comment] 2017-11-14 15:45
Thanks for checking and the feedback @y0ssar1an and @lynic. And just to confirm, your network configurations have default gateways in them, and you've been able to log in and confirm that those gateways should be available from an interface that VMware tools will be able to see?

This is important as this is where the waiter gets its information from.

Just FYI that I am thinking of reverting some of the waiter code back to the old behaviour but just have it skip link-local IPv4. We have new, de-coupled network selection code for the provisioner now that should prioritize routeable addresses as the primary address, falling back to the first available address in the case of issues locating one.

In the meantime, again, you can use `wait_for_guest_net = false` to skip the waiter behaviour altogether.

Thanks!

**Comment by perlei** [comment] 2017-11-17 07:21
We are getting this on ubuntu 16.04, but only with ipv6 only vm's.
i tried setting the wait_for_guest_net = false, but then you only get a more general "timeout". 

As a workaround i changed this line : https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/virtual_machine_helper.go#L141  to return false, instead of the error. This make it "work" for us (using the timout as trigger to proceed).  So there is probably a bug somewhere in the : https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/virtual_machine_helper.go#L88 (waitForGuestVMNet) function.

**Comment by vancluever** [comment] 2017-11-17 16:52
@perlei - when you set `wait_for_guest_net = false`, what is the timeout you are getting instead?

You should not have to hack the waiter, as setting it to false skips it altogether, as seen [here](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_machine.go#L739) and [here](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_machine.go#L1041).

Do you have a default gateway configured? Again, this is the question I've been asking the rest of the reporters on this thread, because the waiter matches gateways with properly configured IPs and netmasks.

Thanks!

**Comment by perlei** [comment] 2017-11-20 09:13
"You should not have to hack the waiter,"
Well we do what we can to keep our self floating. We recently had problems with DNS on our network, and on version 0.2.2 where we do not see this problem we instead have problems with terraform hanging. So we needed to upgrade. And without hacking the waiter, we are unable to create IPv6 enviroments at all, and that is not acceptable. Now its atleast working,

when we configure "wait_for_guest_net = false"  we get a very general error like: 

```
Error applying plan:

2 error(s) occurred:

* vsphere_virtual_machine.controller-46d4d4cf-d35a-490c-a47b-a1c41fc9c4bd-site1: 1 error(s) occurred:

* timeout
* vsphere_virtual_machine.gateway-46d4d4cf-d35a-490c-a47b-a1c41fc9c4bd-site1: 1 error(s) occurred:

* timeout

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

We are mostly spawning 3 vm's at once. So here we can see that 2 out of 3 failed with "timeout"

Regarding the gateway,  yes, we are configuring a gateway 
Here are some of the creation output: 

```
vsphere_virtual_machine.endpoint-46d4d4cf-d35a-490c-a47b-a1c41fc9c4bd-site1: Creating...
  datacenter:                             "" => "dc2devops"
  detach_unknown_disks_on_delete:         "" => "false"
  disk.#:                                 "" => "1"
  disk.1451691130.bootable:               "" => ""
  disk.1451691130.controller_type:        "" => "scsi"
  disk.1451691130.datastore:              "" => "DX90:SAS:R5:V01:D0-23"
  disk.1451691130.iops:                   "" => ""
  disk.1451691130.keep_on_remove:         "" => ""
  disk.1451691130.key:                    "" => "<computed>"
  disk.1451691130.name:                   "" => ""
  disk.1451691130.size:                   "" => ""
  disk.1451691130.template:               "" => "terraform-endpoint-template"
  disk.1451691130.type:                   "" => "eager_zeroed"
  disk.1451691130.uuid:                   "" => "<computed>"
  disk.1451691130.vmdk:                   "" => ""
  dns_servers.#:                          "" => "1"
  dns_servers.0:                          "" => "fd00:ffff:a:93:172:17:93:10"
  domain:                                 "" => "devops"
  enable_disk_uuid:                       "" => "false"
  folder:                                 "" => "Devops Environments"
  gateway:                                "" => "fd00:ffff:a:317::254"
  linked_clone:                           "" => "true"
  memory:                                 "" => "1024"
  memory_reservation:                     "" => "0"
  moid:                                   "" => "<computed>"
  name:                                   "" => "endpoint-46d4d4cf-d35a-490c-a47b-a1c41fc9c4bd-site1"
  network_interface.#:                    "" => "1"
  network_interface.0.adapter_type:       "" => "vmxnet3"
  network_interface.0.ip_address:         "" => "<computed>"
  network_interface.0.ipv4_address:       "" => "<computed>"
  network_interface.0.ipv4_gateway:       "" => "<computed>"
  network_interface.0.ipv4_prefix_length: "" => "<computed>"
  network_interface.0.ipv6_address:       "" => "fd00:ffff:a:317::2"
  network_interface.0.ipv6_gateway:       "" => "fd00:ffff:a:317::254"
  network_interface.0.ipv6_prefix_length: "" => "64"
  network_interface.0.key:                "" => "<computed>"
  network_interface.0.label:              "" => "DevOps 317"
  network_interface.0.mac_address:        "" => "<computed>"
  network_interface.0.subnet_mask:        "" => "<computed>"
  power_state:                            "" => "poweredOn"
  skip_customization:                     "" => "false"
  time_zone:                              "" => "Etc/UTC"
  uuid:                                   "" => "<computed>"
  vcpu:                                   "" => "1"
  wait_for_customization_timeout:         "" => "10"
  wait_for_guest_net:                     "" => "false"
vsphere_virtual_machine.controller-46d4d4cf-d35a-490c-a47b-a1c41fc9c4bd-site1: Creating...
  datacenter:                             "" => "dc2devops"
  detach_unknown_disks_on_delete:         "" => "false"
  disk.#:                                 "" => "2"
  disk.3740851668.bootable:               "" => ""
  disk.3740851668.controller_type:        "" => "scsi"
  disk.3740851668.datastore:              "" => "DX90:SAS:R5:V01:D0-23"
  disk.3740851668.iops:                   "" => ""
  disk.3740851668.keep_on_remove:         "" => ""
  disk.3740851668.key:                    "" => "<computed>"
  disk.3740851668.name:                   "" => "xdp-install-disk"
  disk.3740851668.size:                   "" => "30"
  disk.3740851668.template:               "" => ""
  disk.3740851668.type:                   "" => "thin"
  disk.3740851668.uuid:                   "" => "<computed>"
  disk.3740851668.vmdk:                   "" => ""
  disk.3918603429.bootable:               "" => ""
  disk.3918603429.controller_type:        "" => "scsi"
  disk.3918603429.datastore:              "" => "DX90:SAS:R5:V01:D0-23"
  disk.3918603429.iops:                   "" => ""
  disk.3918603429.keep_on_remove:         "" => ""
  disk.3918603429.key:                    "" => "<computed>"
  disk.3918603429.name:                   "" => ""
  disk.3918603429.size:                   "" => ""
  disk.3918603429.template:               "" => "devops-template"
  disk.3918603429.type:                   "" => "eager_zeroed"
  disk.3918603429.uuid:                   "" => "<computed>"
  disk.3918603429.vmdk:                   "" => ""
  dns_servers.#:                          "" => "1"
  dns_servers.0:                          "" => "fd00:ffff:a:93:172:17:93:10"
  domain:                                 "" => "devops"
  enable_disk_uuid:                       "" => "false"
  folder:                                 "" => "Devops Environments"
  gateway:                                "" => "fd00:ffff:a:318::254"
  linked_clone:                           "" => "true"
  memory:                                 "" => "20480"
  memory_reservation:                     "" => "0"
  moid:                                   "" => "<computed>"
  name:                                   "" => "controller-46d4d4cf-d35a-490c-a47b-a1c41fc9c4bd-site1"
  network_interface.#:                    "" => "1"
  network_interface.0.adapter_type:       "" => "vmxnet3"
  network_interface.0.ip_address:         "" => "<computed>"
  network_interface.0.ipv4_address:       "" => "<computed>"
  network_interface.0.ipv4_gateway:       "" => "<computed>"
  network_interface.0.ipv4_prefix_length: "" => "<computed>"
  network_interface.0.ipv6_address:       "" => "fd00:ffff:a:318::1"
  network_interface.0.ipv6_gateway:       "" => "fd00:ffff:a:318::254"
  network_interface.0.ipv6_prefix_length: "" => "64"
  network_interface.0.key:                "" => "<computed>"
  network_interface.0.label:              "" => "DevOps 318"
  network_interface.0.mac_address:        "" => "<computed>"
  network_interface.0.subnet_mask:        "" => "<computed>"
  power_state:                            "" => "poweredOn"
  skip_customization:                     "" => "false"
  time_zone:                              "" => "Etc/UTC"
  uuid:                                   "" => "<computed>"
  vcpu:                                   "" => "3"
  wait_for_customization_timeout:         "" => "10"
  wait_for_guest_net:                     "" => "false"
vsphere_virtual_machine.gateway-46d4d4cf-d35a-490c-a47b-a1c41fc9c4bd-site1: Creating...
  datacenter:                             "" => "dc2devops"
  detach_unknown_disks_on_delete:         "" => "false"
  disk.#:                                 "" => "2"
  disk.3740851668.bootable:               "" => ""
  disk.3740851668.controller_type:        "" => "scsi"
  disk.3740851668.datastore:              "" => "DX90:SAS:R5:V01:D0-23"
  disk.3740851668.iops:                   "" => ""
  disk.3740851668.keep_on_remove:         "" => ""
  disk.3740851668.key:                    "" => "<computed>"
  disk.3740851668.name:                   "" => "xdp-install-disk"
  disk.3740851668.size:                   "" => "30"
  disk.3740851668.template:               "" => ""
  disk.3740851668.type:                   "" => "thin"
  disk.3740851668.uuid:                   "" => "<computed>"
  disk.3740851668.vmdk:                   "" => ""
  disk.3918603429.bootable:               "" => ""
  disk.3918603429.controller_type:        "" => "scsi"
  disk.3918603429.datastore:              "" => "DX90:SAS:R5:V01:D0-23"
  disk.3918603429.iops:                   "" => ""
  disk.3918603429.keep_on_remove:         "" => ""
  disk.3918603429.key:                    "" => "<computed>"
  disk.3918603429.name:                   "" => ""
  disk.3918603429.size:                   "" => ""
  disk.3918603429.template:               "" => "devops-template"
  disk.3918603429.type:                   "" => "eager_zeroed"
  disk.3918603429.uuid:                   "" => "<computed>"
  disk.3918603429.vmdk:                   "" => ""
  dns_servers.#:                          "" => "1"
  dns_servers.0:                          "" => "fd00:ffff:a:93:172:17:93:10"
  domain:                                 "" => "devops"
  enable_disk_uuid:                       "" => "false"
  folder:                                 "" => "Devops Environments"
  gateway:                                "" => "fd00:ffff:a:318::254"
  linked_clone:                           "" => "true"
  memory:                                 "" => "5120"
  memory_reservation:                     "" => "0"
  moid:                                   "" => "<computed>"
  name:                                   "" => "gateway-46d4d4cf-d35a-490c-a47b-a1c41fc9c4bd-site1"
  network_interface.#:                    "" => "2"
  network_interface.0.adapter_type:       "" => "vmxnet3"
  network_interface.0.ip_address:         "" => "<computed>"
  network_interface.0.ipv4_address:       "" => "<computed>"
  network_interface.0.ipv4_gateway:       "" => "<computed>"
  network_interface.0.ipv4_prefix_length: "" => "<computed>"
  network_interface.0.ipv6_address:       "" => "fd00:ffff:a:318::2"
  network_interface.0.ipv6_gateway:       "" => "fd00:ffff:a:318::254"
  network_interface.0.ipv6_prefix_length: "" => "64"
  network_interface.0.key:                "" => "<computed>"
  network_interface.0.label:              "" => "DevOps 318"
  network_interface.0.mac_address:        "" => "<computed>"
  network_interface.0.subnet_mask:        "" => "<computed>"
  network_interface.1.adapter_type:       "" => "vmxnet3"
  network_interface.1.ip_address:         "" => "<computed>"
  network_interface.1.ipv4_address:       "" => "<computed>"
  network_interface.1.ipv4_gateway:       "" => "<computed>"
  network_interface.1.ipv4_prefix_length: "" => "<computed>"
  network_interface.1.ipv6_address:       "" => "fd00:ffff:a:317::1"
  network_interface.1.ipv6_gateway:       "" => "<computed>"
  network_interface.1.ipv6_prefix_length: "" => "64"
  network_interface.1.key:                "" => "<computed>"
  network_interface.1.label:              "" => "DevOps 317"
  network_interface.1.mac_address:        "" => "<computed>"
  network_interface.1.subnet_mask:        "" => "<computed>"
  power_state:                            "" => "poweredOn"
  skip_customization:                     "" => "false"
  time_zone:                              "" => "Etc/UTC"
  uuid:                                   "" => "<computed>"
  vcpu:                                   "" => "2"
  wait_for_customization_timeout:         "" => "10"
  wait_for_guest_net:                     "" => "false"
```

Hope this helps,

**Comment by lynic** [comment] 2017-11-20 09:21
setting "wait_for_guest_net = false" didn't work for me, but after   I update my vcenter version ,  this problem  gone away.

**Comment by vancluever** [comment] 2017-11-20 15:59
@perlei the IPv6 part is interesting and good to know - are you working in an IPv6-exclusive environment? I see that you don't have any IPv4 data in your output.

I will add an IPv6-only test today and see if I can reproduce.

**Comment by vancluever** [comment] 2017-11-20 22:35
@perlei - just an update on my testing. I've uncovered what's more than likely the root cause here. I was able to reproduce this with the default timeout that we have in the guest network waiter (and the only setting in v0.4.2, but in the next version the timeout will be configurable).

The issue stems from the fact that at minimum, you have to have DHCP in the IPv4 settings in the customization specification. If you don't have a DHCP server on the network when you configure IPv6 only, which ultimately happens is that the initial boot will hang looking for an IPv4 address. This DHCP timeout on Ubuntu is around 5 minutes, which is the default value for the guest network waiter.

The solution in the new version of the resource will be to either adjust the value of the waiter (now called `wait_for_guest_net_timeout`) to a value past this DHCP timeout (ie: 10 minutes instead of the default 5), or just to disable it altogether (by setting a zero or negative value). The skip logic has also been moved to the waiter, which returns immediately if the timeout is < 1.

You can watch for updates on #244 and we are working to have it released by the end of the month.

Thanks!

**Comment by perlei** [comment] 2017-11-21 13:13
We never use any dhcp at all for our enviroments. We use terraform to spawn up test enviroments. So enviroments use ipv4 some ipv6 and some mixed. we dont use dhcp in our vm's at all, we want control over what enviroments have what ip.

**Comment by vancluever** [comment] 2017-11-21 16:46
@perlei - in this case, your two course of actions were the ones I mentioned - you will either need to disable the waiter or increase the timeout past what the DHCP timeout on your own machine, unless you have set up the template in a way that allows the machine to get past the initial DHCP timeout on launch so that VMware tools launches and starts reporting IPs to the vSphere. You cannot set IPv4 to disabled in a customization specification.

**Comment by kmott** [comment] 2017-12-27 21:25
I am running in to this consistently with vCenter 6.0 and Debian 8 cloned from template VMs.  I can provide additional debug logs via direct message, as required.  Our environment uses DHCP for the cloned VMs, but terraform never seems to pick up the IP address reported by open-vm-tools on the VM (even though I can open a separate terminal and SSH to it directly).  Setting wait_for_guest_net_timeout=0 skips past the guest networking, but then leaves the 'Host' field empty for the next provisioner (Chef, in our case).

**Comment by m4r10k** [comment] 2018-01-11 17:58
I am running vCenter 6.5 and trying with LinuxKit. Open Vmware Tools are running and recognized by vCenter, dhcp leased ip address is visible. But unfortunately the terraform plan is running into the time-out. I am booting from iso, I am not cloning.

### output
```
  shutdown_wait_timeout:                     "" => "3"
  swap_placement_policy:                     "" => "inherit"
  uuid:                                      "" => "<computed>"
  vmware_tools_status:                       "" => "<computed>"
  vmx_path:                                  "" => "<computed>"
  wait_for_guest_net_timeout:                "" => "5"
vsphere_virtual_machine.vm: Still creating... (10s elapsed)
vsphere_virtual_machine.vm: Still creating... (20s elapsed)
vsphere_virtual_machine.vm: Still creating... (30s elapsed)
vsphere_virtual_machine.vm: Still creating... (40s elapsed)
vsphere_virtual_machine.vm: Still creating... (50s elapsed)
vsphere_virtual_machine.vm: Still creating... (1m0s elapsed)
vsphere_virtual_machine.vm: Still creating... (1m10s elapsed)
vsphere_virtual_machine.vm: Still creating... (1m20s elapsed)
vsphere_virtual_machine.vm: Still creating... (1m30s elapsed)
vsphere_virtual_machine.vm: Still creating... (1m40s elapsed)
vsphere_virtual_machine.vm: Still creating... (1m50s elapsed)
vsphere_virtual_machine.vm: Still creating... (2m0s elapsed)
vsphere_virtual_machine.vm: Still creating... (2m10s elapsed)
vsphere_virtual_machine.vm: Still creating... (2m20s elapsed)
vsphere_virtual_machine.vm: Still creating... (2m30s elapsed)
vsphere_virtual_machine.vm: Still creating... (2m40s elapsed)
vsphere_virtual_machine.vm: Still creating... (2m50s elapsed)
vsphere_virtual_machine.vm: Still creating... (3m0s elapsed)
vsphere_virtual_machine.vm: Still creating... (3m10s elapsed)
vsphere_virtual_machine.vm: Still creating... (3m20s elapsed)
vsphere_virtual_machine.vm: Still creating... (3m30s elapsed)
vsphere_virtual_machine.vm: Still creating... (3m40s elapsed)
vsphere_virtual_machine.vm: Still creating... (3m50s elapsed)
vsphere_virtual_machine.vm: Still creating... (4m0s elapsed)
vsphere_virtual_machine.vm: Still creating... (4m10s elapsed)
vsphere_virtual_machine.vm: Still creating... (4m20s elapsed)
vsphere_virtual_machine.vm: Still creating... (4m30s elapsed)
vsphere_virtual_machine.vm: Still creating... (4m40s elapsed)
vsphere_virtual_machine.vm: Still creating... (4m50s elapsed)
vsphere_virtual_machine.vm: Still creating... (5m0s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.vm: 1 error(s) occurred:

* vsphere_virtual_machine.vm: timeout waiting for a routeable interface

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
### version
$ ./terraform version
Terraform v0.11.2
+ provider.vsphere v1.1.1

### screenshot
![image](https://user-images.githubusercontent.com/9364572/34838815-c38c7bd6-f6ff-11e7-890d-819d0dfaef58.png)

**Comment by vancluever** [comment] 2018-01-11 18:15
Thanks everyone for the feedback.

We will be making some changes to the network waiter to make the routeable portion opt-out, as mentioned in #337. Keep an eye out for this in future releases.

**Comment by m4r10k** [comment] 2018-01-16 12:40
@vancluever to let you know. Working with an Ubuntu 16.0.4 VMware template and cloning it, does work without any hassle. So, it seems like, that my report is specific to LinuxKit Boot from Iso

**Comment by sdemura** [comment] 2018-02-02 21:04
I'm also seeing this on Ubuntu 14.04, which as much as I'd love to get away from, I still can't.

**Comment by sofixa** [comment] 2018-04-10 11:54
I have the same issue with Debian 8 and 9 on 6.5, running open-vm-tools and a simple clone from template timeouts even though the machine gets an IP from DHCP.

**Comment by vancluever** [comment] 2018-04-13 17:49
Hey all, #470 has now been merged which allows you to control the routable behaviour of the network waiter. Keep an eye out for 1.4.1 which will probably be out this week!

**Closed by vancluever** 2018-04-13 17:49 UTC
Labels: enhancement

**Comment by arctiqjacob** [comment] 2020-01-14 01:34
I was having the same issue where my nic was showing up disconnected when I had a customize config. 
I dug a bit and found the following error in `/var/log/vmware-imc/toolsDeployPkg.log`: `Customization command failed: Failed to create bus connection: No such file or directory`

I fixed this by adding `After=dbus.service` in my `/lib/systemd/system/open-vm-tools.service` and then re-cloning the template.

Re-running my terraform code with that updated template successfully fixed my error.
