### ISSUE TITLE
Adding 2nd disk error disk.0: cannot assign disk: unit number 0 on SCSI bus 0 is in use

### ISSUE THREAD

**Issue by hmalinov** [terraform-providers/terraform-provider-vsphere#569] opened 2018-07-18 12:07 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version

./terraform -version
Terraform v0.11.7
+ provider.google v1.4.0
+ provider.vsphere v1.6.0

### vSphere Provider Version

./terraform -version
Terraform v0.11.7
+ provider.google v1.4.0
+ provider.vsphere v1.6.0

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "hma-test_kiev_elex_be" {
  datastore_id          = "${data.vsphere_datastore.ds1test.id}"
  resource_pool_id      = "${data.vsphere_resource_pool.pool.id}"
  guest_id              = "${data.vsphere_virtual_machine.template_rhel74.guest_id}"
  scsi_type             = "${data.vsphere_virtual_machine.template_rhel74.scsi_type}"

  name          = "hma-test.kiev.elex.be"
  num_cpus      = 2
  memory        = 3072

  cpu_hot_add_enabled           = true
  cpu_hot_remove_enabled        = true
  memory_hot_add_enabled        = true
  enable_logging                = true
  sync_time_with_host		= true

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template_rhel74.network_interface_types[0]}"
  }

  disk {
    label = "hma-test.kiev.elex.be.vmdk"
    size = "${data.vsphere_virtual_machine.template_rhel74.disks.0.size}"
    thin_provisioned = "${data.vsphere_virtual_machine.template_rhel74.disks.0.thin_provisioned}"
  }

  disk {
    label = "mydisk.vmdk"
    size = 2
    unit_number = 1
    thin_provisioned = true
  }

  lifecycle {
    ignore_changes = ["disk.0.disk_sharing", "disk.0.datastore_id", "datastore_id", "disk.0", "disk.#", "clone.0", "clone.#"]
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template_rhel74.id}"
    timeout = 60 

    customize {
      linux_options {
        host_name = "hma-test"
        domain    = "${var.domain}"
      }

      network_interface {
        ipv4_address = "10.38.0.178"
        ipv4_netmask = 20
      }

      ipv4_gateway = "${var.gateway}"
      dns_server_list = ["${var.dns_servers}"]
      dns_suffix_list = ["${var.domain}"]
    }
  }

  connection {
    type     = "ssh"
    user     = "root"
    password = "${chomp(base64decode(module.global.rootpw))}"
  }

  provisioner "file" {
    source      = "${var.tf_remote_scripts}"
    destination = "${var.tf_remote_scripts_dest}/"
  }

  provisioner "file" {
    source      = "vsphere/global/files/${lookup(module.global.os_repo, "rhel74")}"
    destination = "/etc/yum.repos.d/saltstack.repo"
  }

  provisioner "remote-exec" {
    inline = [
      "chmod 755 ${var.tf_remote_scripts_dest}/${var.tf_remote_exec}",
      "${var.tf_remote_scripts_dest}/${var.tf_remote_exec}"
    ]
  }
}

```

### Expected Behavior

Add a second disk to the virtual machine 

```hcl
  disk {
    label = "mydisk.vmdk"
    size = 2
    unit_number = 1
    thin_provisioned = true
  }
```

### Actual Behavior

```
./terraform apply -target module.vsphere.module.vsphere-kiev.vsphere_virtual_machine.hma-test_kiev_elex_be
data.vsphere_datacenter.dc: Refreshing state...
data.vsphere_network.network: Refreshing state...
data.vsphere_resource_pool.pool: Refreshing state...
data.vsphere_datastore.ds1test: Refreshing state...
data.vsphere_virtual_machine.template_rhel74: Refreshing state...
vsphere_virtual_machine.hma-test_kiev_elex_be: Refreshing state... (ID: 4216a86e-e1fb-1f31-b4ba-76ddfb5b653f)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.vsphere.module.vsphere-kiev.vsphere_virtual_machine.hma-test_kiev_elex_be
      disk.#:                  "1" => "2"
      disk.0.attach:           "false" => "false"
      disk.0.datastore_id:     "datastore-1445" => "<computed>"
      disk.0.device_address:   "scsi:0:0" => <computed>
      disk.0.disk_mode:        "persistent" => "persistent"
      disk.0.disk_sharing:     "sharingNone" => "sharingNone"
      disk.0.eagerly_scrub:    "false" => "false"
      disk.0.io_limit:         "-1" => "-1"
      disk.0.io_reservation:   "0" => "0"
      disk.0.io_share_count:   "1000" => "0"
      disk.0.io_share_level:   "normal" => "normal"
      disk.0.keep_on_remove:   "false" => "false"
      disk.0.key:              "2000" => "0"
      disk.0.label:            "" => "hma-test.kiev.elex.be.vmdk"
      disk.0.name:             "hma-test.kiev.elex.be/hma-test.kiev.elex.be.vmdk" => ""
      disk.0.path:             "hma-test.kiev.elex.be/hma-test.kiev.elex.be.vmdk" => <computed>
      disk.0.size:             "100" => "100"
      disk.0.thin_provisioned: "true" => "true"
      disk.0.unit_number:      "0" => "0"
      disk.0.uuid:             "6000C29f-1539-e30e-32ba-dba59596c383" => <computed>
      disk.0.write_through:    "false" => "false"
      disk.1.attach:           "" => "false"
      disk.1.datastore_id:     "" => "<computed>"
      disk.1.device_address:   "" => <computed>
      disk.1.disk_mode:        "" => "persistent"
      disk.1.disk_sharing:     "" => "sharingNone"
      disk.1.eagerly_scrub:    "" => "false"
      disk.1.io_limit:         "" => "-1"
      disk.1.io_reservation:   "" => "0"
      disk.1.io_share_count:   "" => "0"
      disk.1.io_share_level:   "" => "normal"
      disk.1.keep_on_remove:   "" => "false"
      disk.1.key:              "" => "0"
      disk.1.label:            "" => "mydisk.vmdk"
      disk.1.path:             "" => <computed>
      disk.1.size:             "" => "2"
      disk.1.thin_provisioned: "" => "true"
      disk.1.unit_number:      "" => "1"
      disk.1.uuid:             "" => <computed>
      disk.1.write_through:    "" => "false"


Plan: 0 to add, 1 to change, 0 to destroy.


module.vsphere.module.vsphere-kiev.vsphere_virtual_machine.hma-test_kiev_elex_be: Modifying... (ID: 4216a86e-e1fb-1f31-b4ba-76ddfb5b653f)
  disk.#:                  "1" => "2"
  disk.0.attach:           "false" => "false"
  disk.0.datastore_id:     "datastore-1445" => "<computed>"
  disk.0.device_address:   "scsi:0:0" => "<computed>"
  disk.0.disk_mode:        "persistent" => "persistent"
  disk.0.disk_sharing:     "sharingNone" => "sharingNone"
  disk.0.eagerly_scrub:    "false" => "false"
  disk.0.io_limit:         "-1" => "-1"
  disk.0.io_reservation:   "0" => "0"
  disk.0.io_share_count:   "1000" => "0"
  disk.0.io_share_level:   "normal" => "normal"
  disk.0.keep_on_remove:   "false" => "false"
  disk.0.key:              "2000" => "0"
  disk.0.label:            "" => "hma-test.kiev.elex.be.vmdk"
  disk.0.name:             "hma-test.kiev.elex.be/hma-test.kiev.elex.be.vmdk" => ""
  disk.0.path:             "hma-test.kiev.elex.be/hma-test.kiev.elex.be.vmdk" => "<computed>"
  disk.0.size:             "100" => "100"
  disk.0.thin_provisioned: "true" => "true"
  disk.0.unit_number:      "0" => "0"
  disk.0.uuid:             "6000C29f-1539-e30e-32ba-dba59596c383" => "<computed>"
  disk.0.write_through:    "false" => "false"
  disk.1.attach:           "" => "false"
  disk.1.datastore_id:     "" => "<computed>"
  disk.1.device_address:   "" => "<computed>"
  disk.1.disk_mode:        "" => "persistent"
  disk.1.disk_sharing:     "" => "sharingNone"
  disk.1.eagerly_scrub:    "" => "false"
  disk.1.io_limit:         "" => "-1"
  disk.1.io_reservation:   "" => "0"
  disk.1.io_share_count:   "" => "0"
  disk.1.io_share_level:   "" => "normal"
  disk.1.keep_on_remove:   "" => "false"
  disk.1.key:              "" => "0"
  disk.1.label:            "" => "mydisk.vmdk"
  disk.1.path:             "" => "<computed>"
  disk.1.size:             "" => "2"
  disk.1.thin_provisioned: "" => "true"
  disk.1.unit_number:      "" => "1"
  disk.1.uuid:             "" => "<computed>"
  disk.1.write_through:    "" => "false"

Error: Error applying plan:

1 error(s) occurred:

* module.vsphere.module.vsphere-kiev.vsphere_virtual_machine.hma-test_kiev_elex_be: 1 error(s) occurred:

* vsphere_virtual_machine.hma-test_kiev_elex_be: disk.0: cannot assign disk: unit number 0 on SCSI bus 0 is in use

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
I am actually trying to add a second disk on an existing machine. 
Previously I used an ignore_changes = ["disk.0.disk_sharing", "disk.0.datastore_id", "datastore_id", "disk.0", "disk.#", "clone.0", "clone.#"]  to avoid reinstalling he VMs when the template is changed.

**Comment by bill-rich** [comment] 2018-07-18 18:43
Hi @hmalinov! That is an interesting problem you're running into. I've got a couple questions to help me reproduce the issue and figure out what is going on. Can you provide more information on what is happening out of band on VMware with the existing virtual machine? Are you using `ignore_changes` when you run into the issue, or does that resolve it for you? Does your source template have multiple disks?

Thanks!

**Comment by hmalinov** [comment] 2018-07-19 06:39
Hi @bill-rich 

My source template has only one disk. Like I explained I do not want to trigger reinstallation of the vmware machines if the template is updated so I use ignore_changes  with the vmware machine initial creation.

If I try a terraform apply before adding the second disk in the .tf file, it does not see any changes to apply. Once I add the second disk in the .tf, you can see the result above.

On the virtual machines nothing happens. I do not even see an error in the vCenter.
I will be glad to provide more information if needed.

**Comment by hmalinov** [comment] 2018-08-15 12:52
Hi @bill-rich , kindly asking if there is any update for this issue?

**Comment by mbond-igs** [comment] 2019-02-21 18:22
I have this similar issue but I am able to add and change disks just fine, this problem happens we change the Domain User Name and Password, that is used for joining to the domain, in the terraform files. This makes using this with a team nearly impossible.

**Comment by bill-rich** [comment] 2019-06-26 06:22
Same root cause as #357. Closing to track the issue there.

**Closed by bill-rich** 2019-06-26 06:22 UTC
Labels: bug

**Comment by vabhishek6** [comment] 2019-11-22 16:51
if you're still having this issue I would recommend explicitly mentioning `unit_number = 1` in your second disk 

`  disk {
    label            = "disk1"
    size             = "${data.vsphere_virtual_machine.template.disks.1.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.1.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.1.thin_provisioned}"
    unit_number = 1
  }
`
