### ISSUE TITLE
The vsphere provider lies when I set a new IP

### ISSUE THREAD

**Issue by johnjelinek** [terraform-providers/terraform-provider-vsphere#200] opened 2017-10-11 15:49 UTC
### Terraform Version
`Terraform v0.10.7`

### Affected Resource(s)
- vsphere_virtual_machine

### Terraform Configuration Files
```hcl
# Configure the VMware vSphere Provider
provider "vsphere" {
  user           = ""
  password       = ""
  vsphere_server = ""

  # if you have a self-signed cert
  allow_unverified_ssl = true
}

# Create a virtual machine within the folder
resource "vsphere_virtual_machine" "abc" {
  name   = "abc"
  vcpu   = 2
  memory = 4096

  network_interface {
    label = "VM Network"
    ipv4_address = "192.168.7.115"
    ipv4_gateway = "192.168.7.254"
    ipv4_prefix_length = "24"
  }

  disk {
    template = "abc"
  }
}

```

### Expected Behavior
Static IP should have been modified

### Actual Behavior
```
vsphere_virtual_machine.abc: Refreshing state... (ID: abc)
vsphere_virtual_machine.abc: Modifying... (ID: abc)
  network_interface.0.ipv4_address: "192.168.7.111" => "192.168.7.115"
vsphere_virtual_machine.abc: Modifications complete after 1s (ID: abc)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
(but it lies! If I run `ip a`, the old IP remains)

### Steps to Reproduce
1. `terraform apply`

**Comment by vancluever** [comment] 2017-10-11 16:27
Hey @johnjelinek, thanks for the bug and sorry you are having trouble!

The fact that IP modification is actually possible in TF without forcing a new resource is actually a bug. During a larger update to the resource coming shortly, we will be reviewing if it's feasible to allow re-customization of a VM as normally this is a one-time thing that's done on cloning. Currently though you can run under the assumption that it's _not_ possible and treat the IP address field as immutable unless you want to re-deploy the VM by tainting it.

Will keep this open as we address this 100% in the new version of the resource.

Thanks!

**Comment by johnjelinek** [comment] 2017-10-11 17:28
Cool, ya -- in previous versions, the resource would be deleted and recreated, I'm fine with that behavior. Also, note: if `NetworkManager` is enabled on your VM, it may disregard whatever IP settings you provide via terraform. I had to disable the service in my VM template before the IP could be set.

**Comment by rismoney** [comment] 2017-10-13 00:49
what is the expected behavior on a label change? should it recreate or not?

**Comment by vancluever** [comment] 2017-10-13 00:56
@rismoney - I've just discovered in the process of working on #10 that unfortunately, label change is `ForceNew` at the moment. :confused: 

As I will be working on the new version of the `vsphere_virtual_machine` resource probably after v0.4.2, this is not being modified at the moment as I'm not too sure of the implications. This will be fixed in the refactor however as changing the network label on a virtual NIC is a pretty routine task that definitely should not be forcing a new resource.

Sorry about the issue here!

**Comment by krzkowalczyk** [comment] 2017-10-16 09:25
@vancluever - I'm glad to hear that you plan to fix NICs management. Right not I'm frightened each time sysadmins are manipulating vnets from vsphere side, and I see a bunch of servers tainted due to difference in network label. 
Maybe it will help you a bit, I spot some time a go this [Issue](url) on other vsphere provider fork, together with [PR](https://github.com/IBM-tfproviders/terraform-provider-vsphere/pull/23) which allows network interfaces manipulation without host recreation.
I've tested in on linux machine, and I was working. Therefore that implementation lack support for windows, maybe this is intended, as to configure interfaces it's needed to call CustomizeVM_Task(), which might trigger sysprep (this is my guessing) and this won't be good.

**Comment by vancluever** [comment] 2017-10-16 15:20
Hey @krzkowalczyk! Took a very brief look at that PR, but indeed I'm aware that `CustomizeVM_Task` can be called separate from the cloning process so I'm wondering how well that behaves 100% with re-customization and if it's stable enough to offer as an option. The fact that you tested it and it worked is good to know and something I will keep in mind!

One of the big things here that I want to address that I'm not 100% too sure if the IBM fork addresses is the current coupling of network interfaces to the customization spec, and the coupling of VM guest net state to the Terraform configuration. This all has been the source of the vast majority of crashes in the resource and seeing as it's not coupled in the API, IMO it should not be coupled in TF. Whether or not we allow re-customization will definitely affect how we proceed here I think, but I want to try as much as possible to ensure that configuration and the state that VMware tools reports do not interfere with each other. If we keep customization `ForceNew`, then we really don't have to worry so much about what the guest net state looks like after a deploy and we can just store it separately - if we do want to allow re-customization, it gets a little complicated again.

All of this stuff will become a lot more obvious as I dive into it over the next few weeks, so stay tuned!

**Comment by rismoney** [comment] 2017-10-16 17:31
@krzkowalczyk  what is your mitigation for sysadmins manipulating vnets?  are you hacking the statefile?  I'm nervous too for fear I could wipe out quite a bit of inf.

**Comment by krzkowalczyk** [comment] 2017-10-17 10:47
@vancluever, my skills in golang development are still under construction, but if you need any help with testing I'm eager to help.
@rismoney, yep, I run weakly 'let's fix the state' activity. Sometimes it's not possible, or too time consuming so then I use ignore_changes directive. Secondly sysadmins doesn't have direct access to terraform. I wrote jenkins pipelines for managing it, code is pulled from git, and the only actions which are available are plan, and apply for specific target. With that it's not possible to hit apply for all environment, you always need to specify a host.
At last, production nodes have set prevent_destroy flag. BTW there is a bug here, because this flag should prevent from applying destructive operations, but it forbids to run a plan when object is tainted.

**Comment by bill-rich** [comment] 2018-05-09 16:48
Hi @krzkowalczyk! 
The virtual machine resource had a lot of work done in the last few months, and it looks like some of those changes have resolved the issue you were running into. Some changes would need to be made to your original configuration, but you shouldn't have problems with IP updates not being applied or fear of losing VMs due to vSphere-side network changes. The IP related attributes for clones have been moved into `network_interface` within  `customize`. Another option is to use `vapp` properties if your template supports them. See [virtual machine customization](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#virtual-machine-customization) or [using vApp properties to supply OVF/OVA configuration](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#using-vapp-properties-to-supply-ovf-ova-configuration) for the specifics on the what can be done with each. Thanks for getting the issue brought up!

**Closed by bill-rich** 2018-05-09 16:48 UTC
Labels: bug
