### ISSUE TITLE
Run plan with existing local state file against resource that has changed crashes Terraform with 'Error: rpc error: code = Unavailable desc = transport is closing'

### ISSUE THREAD

**Issue by pauledavey** [terraform-providers/terraform-provider-vsphere#869] opened 2019-10-16 09:28 UTC
Terraform version: v0.12.10
vSphere Provider version: v1.13.0

I have a simple script to add a portgroup to an ESXi host (as follows)

```
data "vsphere_datacenter" "datacenter" {
  name = "AutomationCore"
}

data "vsphere_host" "esxi_host" {
  name          = "${var.esxi_hostName}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

resource "vsphere_host_port_group" "pg" {
  name                = "PGTerraformTest"
  host_system_id      = "${data.vsphere_host.esxi_host.id}"
  virtual_switch_name = "vSwitch0"
  vlan_id = 4095
  allow_promiscuous = true
}
```

This adds the portgroup to a host specified as a variable correctly. I can plan and apply successfully.
Following this I can run plan again against the same host. It states that the same resource needs to be created again (1 to add) which I find strange. If I attempt to apply it tells me the resource already exists.

If I manually change the vLAN on the portgroup from 4095 to something else (i.e. 999) and then run plan against the host, Terraform crashes. My understanding is that it should show me that there is a difference between the locally saved state file and the deployed portgroup. I have this issue against multiple ESXi hosts.

I have attached the crash.log file to this issue ticket.
[crash.log](https://github.com/terraform-providers/terraform-provider-vsphere/files/3733486/crash.log)

**Comment by koikonom** [comment] 2019-10-30 21:15
HI @pauledavey! Thanks for taking the time to report this issue.

I tried to reproduce this against my own vsphere lab with little success. Can you please reproduce the issue, with the environment variable `TF_LOG` set to `DEBUG` before running terraform, and upload the debug output ?

**Comment by aareet** [comment] 2019-11-21 17:01
I am closing this issue since it has been waiting for a response for 22 days. Please reopen if this is reproducible.

**Closed by aareet** 2019-11-21 17:01 UTC
Labels: crash, waiting-response
