### ISSUE TITLE
Using 'clone' in Life cycle settings causes strange errors 

### ISSUE THREAD

**Issue by serverbaboon** [terraform-providers/terraform-provider-vsphere#764] opened 2019-05-13 17:43 UTC
Hi there,

I am trying to get Terraform to ignore changes in Local Admin password so it does not redeploy the machines again if the local administrator password variable value changes.

If I use 'clone' or 'clone.0.customize.0.windows_options.0.admin_password' in the Life Cycle policy section and then change the admin password value in the script then Terraform now longer wants to redeploy the whole vm, however it wants to edit the disks as shown below.

Not sure is its something to do with the change disk.1.key: "2001" => "0"

Adding "disk" to the lifecycle stops this but then you cannot manage the disk size.

### Terraform Version

Terraform 0.11.13

### vSphere Provider Version
vsphere v1.9.0

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl

provider "vsphere" {
  user           = "My_username"
  password       = "my"
  vsphere_server = "vcenter_server"

  # If you have a self-signed cert
  allow_unverified_ssl = true
}


variable "datacentre" {
  description = "Data Centre to deploy to"
  default = "MYDATACENTER"
}

variable "VSPHERE_PASSWORD" {
  description = "Your password"
}

data "vsphere_datacenter" "vcenter" {
  name = "${var.datacentre}"
}

data "vsphere_virtual_machine" "deployment_template" {
  name          = "_template_2k12std"
  datacenter_id = "${data.vsphere_datacenter.vcenter.id}"
}

data "vsphere_datastore" "target" {
  name          = "NFSSTORE"
  datacenter_id = "${data.vsphere_datacenter.vcenter.id}"
}

data "vsphere_compute_cluster" "target" {
  name          = "DC1CLUSTER"
  datacenter_id = "${data.vsphere_datacenter.vcenter.id}"
}

data "vsphere_network" "nic1_portgroup" {
  name          = "Portgroup1"
  datacenter_id = "${data.vsphere_datacenter.vcenter.id}"
}

data "vsphere_network" "nic2_portgroup" {
  name          = "Portgroup2"
  datacenter_id = "${data.vsphere_datacenter.vcenter.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name = "TERGIT-001"
  count ="1"
  datastore_id           = "${data.vsphere_datastore.target.id}"
  num_cpus               = "2"
  memory                 = "4096"
  guest_id               = "${data.vsphere_virtual_machine.deployment_template.guest_id}"
  annotation             = "Deployed by Terraform"
  memory_hot_add_enabled = "true"
  cpu_hot_add_enabled    = "true"

  //  Stop Terraform from redeploying or changing stuff
  lifecycle {
    ignore_changes = ["annotation", "tags", "clone.0.customize.0.windows_options.0.admin_password", ]
  }

  resource_pool_id = "${data.vsphere_compute_cluster.target.resource_pool_id}"
  scsi_type        = "${data.vsphere_virtual_machine.deployment_template.scsi_type}"
  firmware         = "${data.vsphere_virtual_machine.deployment_template.firmware}"

  network_interface {
    network_id   = "${data.vsphere_network.nic1_portgroup.id}"
    adapter_type = "${data.vsphere_virtual_machine.deployment_template.network_interface_types[0]}"
  }

  network_interface {
    network_id   = "${data.vsphere_network.nic2_portgroup.id}"
    adapter_type = "${data.vsphere_virtual_machine.deployment_template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    thin_provisioned = "${data.vsphere_virtual_machine.deployment_template.disks.0.thin_provisioned}"
    size             = "${data.vsphere_virtual_machine.deployment_template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.deployment_template.disks.0.eagerly_scrub}"
  }

  disk {
    label            = "disk1"
    thin_provisioned = "${data.vsphere_virtual_machine.deployment_template.disks.1.thin_provisioned}"
    size             = "80"
    eagerly_scrub    = "${data.vsphere_virtual_machine.deployment_template.disks.1.eagerly_scrub}"
    unit_number      = 1
  }
  clone {
    template_uuid = "${data.vsphere_virtual_machine.deployment_template.id}"

    customize {
      windows_options {
        computer_name = "TER-GIT-001"

        workgroup             = "GIT-TERRAFORM"
        organization_name     = "Fictious"
        auto_logon            = true
        admin_password        = "Th1sOneIsReallyT0ugh"
        time_zone             = 85
      }

      network_interface {
        ipv4_address    = "10.30.32.20"
        ipv4_netmask    = "24"
        dns_server_list = ["10.30.32.5","10.30.32.6",]
        dns_domain      = "fictious.com"
      }

      network_interface {
        ipv4_address = "10.100.200.20"
        ipv4_netmask = "24"
      }

      ipv4_gateway = "10.30.32.1"
    }
    timeout  = "10"
  }
}


```

### Expected Behavior

Terraform should make no changes.

### Actual Behavior

Terraform wants to change the disks 

Terraform will perform the following actions:

  ~ vsphere_virtual_machine.vm
      disk.#:                  "2" => "2"
      disk.0.attach:           "false" => "false"
      disk.0.datastore_id:     "datastore-xxx" => "<computed>"
      disk.0.device_address:   "scsi:0:0" => <computed>
      disk.0.disk_mode:        "persistent" => "persistent"
      disk.0.disk_sharing:     "sharingNone" => "sharingNone"
      disk.0.eagerly_scrub:    "false" => "false"
      disk.0.io_limit:         "-1" => "-1"
      disk.0.io_reservation:   "0" => "0"
      disk.0.io_share_count:   "1000" => "0"
      disk.0.io_share_level:   "normal" => "normal"
      disk.0.keep_on_remove:   "false" => "false"
      disk.0.key:              "2000" => "0"
      disk.0.label:            "disk0" => "disk0"
      disk.0.path:             "TERGIT-001/TERGIT-001.vmdk" => <computed>
      disk.0.size:             "75" => "75"
      disk.0.thin_provisioned: "true" => "true"
      disk.0.unit_number:      "0" => "0"
      disk.0.uuid:             "6000C29f-12b3-a3b7-ec4f-01edef2c7737" => <computed>
      disk.0.write_through:    "false" => "false"
      disk.1.attach:           "false" => "false"
      disk.1.datastore_id:     "datastore-189" => "<computed>"
      disk.1.device_address:   "scsi:0:1" => <computed>
      disk.1.disk_mode:        "persistent" => "persistent"
      disk.1.disk_sharing:     "sharingNone" => "sharingNone"
      disk.1.eagerly_scrub:    "false" => "false"
      disk.1.io_limit:         "-1" => "-1"
      disk.1.io_reservation:   "0" => "0"
      disk.1.io_share_count:   "1000" => "0"
      disk.1.io_share_level:   "normal" => "normal"
      disk.1.keep_on_remove:   "false" => "false"
      disk.1.key:              "2001" => "0"
      disk.1.label:            "disk1" => "disk1"
      disk.1.path:             "TERGIT-001/TERGIT-001_1.vmdk" => <computed>
      disk.1.size:             "80" => "80"
      disk.1.thin_provisioned: "true" => "true"
      disk.1.unit_number:      "1" => "1"
      disk.1.uuid:             "6000C293-ce60-9243-077a-92144dfcf047" => <computed>
      disk.1.write_through:    "false" => "false"

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Factoids
As you can see the deployment is a multi nic machine.

**Comment by bill-rich** [comment] 2019-06-26 06:23
Same root cause as #357. Closing to track the issue there.

**Closed by bill-rich** 2019-06-26 06:23 UTC
Labels: bug
