### ISSUE TITLE
VM provisioning fails with datastore not found error

### ISSUE THREAD

**Issue by sreekanth-ragi** [terraform-providers/terraform-provider-vsphere#747] opened 2019-04-17 11:24 UTC
Hi there,

I have an issue with not being able to provision an VM instance using the VSphere provider. I get an error saying unable to find datastore.

### Terraform Version

Terraform v0.11.13
+ provider.vsphere v1.10.0

### vSphere Provider Version

provider.vsphere

### Affected Resource(s)

- `vsphere_virtual_machine`

```hcl
provider "vsphere" {
    vsphere_server = "${var.vsphere_server}"
    user = "${var.vsphere_user}"
    password = "${var.vsphere_password}"
    allow_unverified_ssl = true
}


data "vsphere_datacenter" "dc" {
  name          = "${var.datacenter}"
}

data "vsphere_datastore" "ds" {
  name          = "${var.datastore}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

#data "vsphere_datastore_cluster" "ds" {
#  name          = "${var.datastore}"
#  datacenter_id = "${data.vsphere_datacenter.dc.id}"
#}

data "vsphere_virtual_machine" "template" {
  name          = "${var.template}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "${var.network}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "${var.pool}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name              = "${var.name}-${count.index + 1}"
  count             = "${var.count}"
  resource_pool_id  = "${data.vsphere_resource_pool.pool.id}"
  datastore_id      = "${data.vsphere_datastore.ds.id}"

  num_cpus          = "${var.cpu}"
  memory            = "${var.memory}"
  guest_id          = "${data.vsphere_virtual_machine.template.guest_id}"
...
...
}

### Debug Output

Please provide a link to a GitHub Gist containing the complete debug output:
https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the
debug output in the issue; just paste a link to the Gist.

### Expected Behavior

VM instance is successfully provisioned.

### Actual Behavior

Provisioning is failing with error
Error: Error refreshing state: 1 error(s) occurred:

* data.vsphere_datastore.ds: 1 error(s) occurred:

* data.vsphere_datastore.ds: data.vsphere_datastore.ds: error fetching datastore: datastore '<DS Name>' not found

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by sreekanth-ragi** [comment] 2019-04-17 11:33
Following is the link to trace file output:
https://gist.github.com/sreekanth-ragi/d82847bc5dc9fcdc05c54d7c7b9dac63

**Comment by bill-rich** [comment] 2019-04-17 22:06
Hi @sreekanth-ragi! The datastore data source seems to be unable to find the datastore based on the info provided. 

A good way to make sure all the inputs are correct is to use [govc](https://github.com/vmware/govmomi/tree/master/govc). With `govc`, you can use the `ls` sub-command to navigate your vCenter setup. You should be able to just use the name of your datastore, but you can also try using the full path found with `govc`.

If it looks like everything is matching up, but the data source is still not able to find the datastore, please share the full datastore path from `govc` so I can attempt to reproduce the issue.

**Comment by bill-rich** [comment] 2019-05-23 21:42
Closing since there hasn't been a response in a while.

**Closed by bill-rich** 2019-05-23 21:42 UTC
Labels: question, waiting-response
