### ISSUE TITLE
Bulk VM deletion fails during terraform destroy

### ISSUE THREAD

**Issue by Nishmita** [terraform-providers/terraform-provider-vsphere#534] opened 2018-05-23 11:49 UTC
### Terraform Version

nish@ubuntu:~/go/bin$ ./terraform version
Terraform v0.11.7

provider.nsxt v1.0.0
provider.vsphere v1.3.3

### Affected Resource(s)
vsphere_virtual_machine

### Terraform Configuration Files

```
# =====================create VM's ===================================
resource "vsphere_virtual_machine" "vm1" {
  count = 1
  name = "${var.vm_name}"
  #name = "${format("vm_%03d", count.index + 1)}"
  depends_on = ["nsxt_logical_switch.LS1"]

  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  num_cpus = 1
  memory   = 1024
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"
  # Attach the VM to the network data source that refers to the newly created logical switch
  network_interface {
    network_id = "${data.vsphere_network.terraform_testvm.id}"
  }
  disk {
    label            = "test.vmdk"
    size             = "50"
    thin_provisioned = true
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    customize {
      linux_options {
        host_name = "testvm"
        domain    = "test.local"
      }
      network_interface {
        ipv4_address = "${format("%s%d", local.ip_net, count.index + 2)}"
        ipv4_netmask = "24"
      }

      ipv4_gateway = "${local.ip_net}1"
    }
  }
}
```

### Debug Output

Getting below error during cleanup:

Error: Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.vm1 (destroy): 1 error(s) occurred:

1 error(s) occurred:

* vsphere_virtual_machine.vm1: error destroying virtual machine: Post https://60.0.25.68/sdk: context deadline exceeded

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

* vsphere_virtual_machine.vm1 (destroy): 1 error(s) occurred:

* vsphere_virtual_machine.vm1: error destroying virtual machine: Post https://60.0.25.68/sdk: context deadline exceeded

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Expected Behavior
terraform destroy should cleanup all the vm's 

### Actual Behavior

Few VM's are not getting cleaned  

### Steps to Reproduce

Run below commands from 30 clients on the same compute host. 
(We have tried using running on docker containers)
./terraform plan -> success
./terraform apply -> success
./terraform destroy -> failed with error mentioned in debug output section

**Comment by kaizoku0506** [comment] 2018-10-19 18:19
+1

We just hit this while attempting to deploy 10x VMs.

**Comment by bill-rich** [comment] 2018-10-26 23:31
It looks like the API is timing out or the associated tasks are taking a very long time to complete. @Nishmita or @kaizoku0506 can you confirm if Terraform is taking a very long time (9+ minutes) to fail with this error, or is it quicker?

**Comment by bill-rich** [comment] 2018-11-27 23:39
I haven't been able to reproduce the issue. Closing for now.

**Closed by bill-rich** 2018-11-27 23:39 UTC
Labels: bug

**Comment by bredamatt** [comment] 2019-04-05 12:51
Encountered the same issue whilst deploying 10x VMs. The .tfstate is updated, and when trying to destroy the VMs using terraform destroy, the same issue comes up again. 

In the vSphere console, I am also unable to delete the VMs manually. It appears they are "frozen" in the console.
