### ISSUE TITLE
Attribute to specify vpshere_virtual_machine should not be powered on during/after deployment

### ISSUE THREAD

**Issue by ezibode** [terraform-providers/terraform-provider-vsphere#545] opened 2018-06-05 18:12 UTC
**Affected Resource(s)**
- vsphere_virtual_machine

I believe this is an Enhancement request.

I would like to request that an (appropriately declaratively named) attribute be added to the vsphere_virtual_machine resource to allow a virtual machine to be deployed, but not be powered on as part of/at the end of the deployment process. In other words, at the end of a 'terraform apply' I want the virtual machine to exist, but to not have been powered on at all. Maybe an attribute named like powered_on_after_deploy  or power_on_after_deploy that defaults to true, but can be set to false.

I need to be able to mass deploy virtual machines but then power them on individually or in groups at a later time.

**Comment by bill-rich** [comment] 2018-06-07 05:35
Hi @ezibode! Thank you for presenting the use case for a powered on after deploy attribute. I see there would be cases where that would quite be helpful. 

The issue is that there are quite a few other attributes within the virtual machine resource which require the VM be powered on. Introducing the option to leave it powered off could lead to situations where what is in the configuration doesn't really match the actual state of the VM. 

Would it be possible to only add the required resources to your configuration as they are needed?

**Comment by bill-rich** [comment] 2018-06-08 17:40
I'm going to close this as we're not going to implement to avoid straying from infrastructure immutability.

**Closed by bill-rich** 2018-06-08 17:40 UTC
Labels: enhancement

**Comment by ezibode** [comment] 2018-06-09 18:32
Bill,

Thanks for considering the feature request.  I understand why you have chosen not to implement it. In an effort to tie off this thread, I do have a couple of questions. With regards to a resource of type vsphere_virtual_machine, is it effectively stateless when it comes to power state? Meaning it is assumed to always be _Powered On_? The implication being that power state will not be exposed for external modification/tracking and will only be dealt with internally as necessary to fulfill other requests. Is that correct?

Regards,

Ezibode
