### ISSUE TITLE
file provisioner for vsphere vm with 2 nics defaults to wrong nic

### ISSUE THREAD

**Issue by jgs40687** [terraform-providers/terraform-provider-vsphere#720] opened 2019-02-27 18:43 UTC
Hi there,

I am using terraform version 0.11.11 with vsphere provider v1.9.1

### Affected Resource(s) - terraform file provisioner

I am building a Windows 2012 vm with 2 nics, I can IP them fine using ${var.mgmt_ip_address} and ${var.data_ip_address} etc, sort the correct default gateway and which to be blank, add a static route for the one without default gateway using a run_once command, all relatively standard and all works fine

but........I then want to connect using file provisioner to the mgmt IP which is the one that is defined first, but no matter what I put in the "host" entry in connection as per below, it will always try to initiate the connection over the data IP, the one that is defined second, I need to connect over mgmt IP, that is where all the firewall rules are defined

provisioner "file" {
   source       = "${path.module}/scripts/"
   destination  = "C:\\scripts"
   connection   = {
     host       = "${var.mgmt_ip_address}"
     insecure   = true
     type       = "winrm"
     user       = "Administrator"
     password   = "${var.windows_admin_password}"
     agent      = "false"
   }

using the above host entry, it simply ignores it and uses the IP of the data nic. If I hard code the correct IP as the host entry, same, ignores it

I tried ${self.default_ip_address} that seems to resolve to the data IP in my case, the nic defined second. Is there a ${self.<attribute>} I can use that will resolve to the first defined interface? 

in a debug trace I can see the entry for "All IP Addresses" they are listed <one I defined 2nd>, <one I defined 1st>, and I guess as a result the 1 line above it has "Primary IP Address" as the first one listed, which is the one I defined 2nd

so my question is can I change this? can I get file provisioner to connect over my chosen IP not the one it has defaulted to?

Thanks

**Comment by jgs40687** [comment] 2019-02-28 14:14
a terraform show tells me the guest_ip_address.0 is the IP of the nic I added second, and guest_ip_address.1 is the one I added first. I tried host = "${self.guest_ip_address.1}" in the file provisioner connection, it didn't error but simply ignored it and default to the data IP.

I can't simply swap these nics round as it is the mgmt nic (first one) that needs to have the blank default gateway

**Comment by bill-rich** [comment] 2019-03-13 17:47
Hi @jgs40687!

Thats very strange that the `host` option seems to be getting ignored, even if you hard code an address. Can you provide the debug logs and a configuration (minus sensitive data) with a hard coded address?

**Comment by bill-rich** [comment] 2019-04-17 23:48
Closing since I was not able to reproduce and there hasn't been a response in a while. If the issue is still valid, let me know and we can re-open it.

**Closed by bill-rich** 2019-04-17 23:48 UTC
Labels: question, waiting-response
