### ISSUE TITLE
Issue while creating VM with host_system_id parameter

### ISSUE THREAD

**Issue by kpsinghchouhan** [terraform-providers/terraform-provider-vsphere#690] opened 2019-01-22 05:55 UTC
Hi,

I am trying to create a VM using vsphere_virtual_machine. I have a cluster of 3 servers and one resource pool. Due to the IPs available, I have created a vSwitch without an uplink on my first server and created a port group on that switch. I am providing the host_system_id of the first server to create the VM there with the VLAN details. VM is getting created on different host and 'terraform apply' gives error saying not able to configure network.

Terraform Version: v0.11.11

vSphere Provider Version: v1.9.1

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
NA

### Debug Output



### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing
the output of the `crash.log`.

### Expected Behavior

VM gets created.

### Actual Behavior

Error: An error occurred while setting up network properties of the guest OS. See the log file /var/log/vmware-imc/toolsDeployPkg.log in the guest OS for details.

VM got created on wrong host without network configuration.

When I run Terraform second time, the VM gets migrated to correct host but network-interface remains disconnected. I need to manually connect it by editing VM setting.

I tried changing value of following wait parameters but got same error.
wait_for_guest_net_timeout = -1 
wait_for_guest_net_routable = false
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids



### References

**Comment by bill-rich** [comment] 2019-01-30 17:41
Hi @kpsinghchouhan! Sorry you're running into this issue. Can you please provide details on your vSphere and vCenter versions? I've seen issues with the `host_system_id` on 6.7, and a workaround was added a while back, but it would not work in your configuration since some resources are only available on the one host.

**Comment by chuanran** [comment] 2019-03-16 04:19
Hi @bill-rich , I have some similar issue as @kpsinghchouhan stated, I tried to use `host_system_id` in `resource "vsphere_virtual_machine" "vm"`, but seems the vm is not always provisioned to the specified host, instead, sometimes it is provisioned under a different host. following is the version of vcenter version

```
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.7.0
Build:        11727113
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.7.1
Product ID:   vpx
```

**Comment by llomgui** [comment] 2019-05-04 20:21
Hi,

I found a workaround, if you want to specify host_system_id parameter, you also need to specify the datastore of this host. Do not use your vsanDatastore. Your VMs will be created without any error.

**Comment by vaneyckt** [comment] 2019-07-01 17:09
@llomgui would you by any chance happen to remember some more detail about how you solved this?

**Comment by llomgui** [comment] 2019-07-03 08:48
@vaneyckt The workaround doesn't work for you?

**Comment by vaneyckt** [comment] 2019-07-03 09:31
@llomgui we dug into it some more on our end and we think we've found the issue. It looks like what's happening is that VMware is getting instructed to deploy the VM on the correct hypervisor, but then vMotion kicks in and moves the VM to another hypervisor in the same pool. We're gonna try again soon on a VMware setup that has vMotion disabled.

**Comment by bill-rich** [comment] 2019-07-03 23:01
Is this one resolved? I don't want to close the issue if there is still an issue with creating VMs on specific hosts, but if the problem is vMotion moving the VMs after they're created, there isn't much to be done on the provider side. 

Thanks!

**Comment by vaneyckt** [comment] 2019-07-04 09:44
@bill-rich I dont know yet. I'm not US based, but am working with US based colleagues on this, and with 4th of July coming up I probably wont know until end of next week

**Comment by vaneyckt** [comment] 2019-07-16 16:39
@bill-rich this is working for us now. Looks like vMotion was to blame for my issue.

**Comment by Boran** [comment] 2019-07-17 08:50
When you say "disable vmotion" I presume you mean disable DRS. But disabling DRS is a bit dramatic - no more automatic balancing/scheduling of resources. A solution needs to be found without having to do that - how about adding VM to a DRS affinity group during creation?

**Comment by aareet** [comment] 2019-08-29 15:20
Closing since Jul 16 comment from @vaneyckt indicates issue was related to vMotion.

**Closed by aareet** 2019-08-29 15:20 UTC
Labels: bug, question-vsphere

**Comment by Boran** [comment] 2019-08-29 17:40
I don’t think this should be closed . A solution needs to be found to allow terraform to create a VM in an environment where vmotion (I think DRS is what is meant by that above) is enabled - especially in a multi-site environment.
Drs used host/vm groups to assign VMs to hosts for « automated vmotion ». So the clean way would be to assign a new vm to an appropriate group on creation with terraform.
