### ISSUE TITLE
Terraform crash when refreshing state

### ISSUE THREAD

**Issue by javefang** [terraform-providers/terraform-provider-vsphere#215] opened 2017-10-20 15:46 UTC
### Terraform Version
0.10.7

### vSphere Provider Version

0.4.2

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "dns_a_record_set" "etcd" {
  count     = "${var.etcd_nodes}"
  zone      = "${var.dns_domain}."
  name      = "${element(vsphere_virtual_machine.etcd.*.name, count.index)}"
  ttl       = 60
  addresses = [
    "${element(vsphere_virtual_machine.etcd.*.network_interface.0.ipv4_address, count.index)}"
  ]
}

resource "vsphere_virtual_machine" "etcd" {
  count                          = "${var.etcd_nodes}"
  name                           = "${element(data.template_file.node_name.*.rendered, count.index)}"
  folder                         = "${var.vmware_folder}"
  cluster                        = "${var.vmware_cluster}"
  vcpu                           = "${var.etcd_node_cpu}"
  memory                         = "${var.etcd_node_memory}"
  datacenter                     = "${var.vmware_datacenter}"
  skip_customization             = true
  
  cdrom {
    datastore = "${var.vmware_datastore}"
    path      = "${var.vmware_userdata_path}/${element(data.template_file.node_name.*.rendered, count.index)}.iso"
  }
  
  network_interface {
    label = "${var.vmware_network_label}"
  }
  
  disk {
    type      = "thin"
    datastore = "${var.vmware_datastore}"
    template  = "Packer/etcd-${var.etcd_version}"
  }
  
  disk {
    datastore      = "${var.vmware_datastore}"
    vmdk           = "${element(vsphere_virtual_disk.etcd_data.*.vmdk_path, count.index)}"
  }
  
  custom_configuration_parameters = {
    env  = "${var.env}"
    role = "${var.role}"
    tag  = "${var.tag}"
  }
  
  depends_on = [
    "vsphere_file.etcd_userdata"
  ]
}

resource "vsphere_virtual_disk" "etcd_data" {
  count         = "${var.etcd_nodes}"
  size          = "${var.etcd_data_vol_size}"
  vmdk_path     = "${var.vmware_vmdk_path}/${element(data.template_file.node_name.*.rendered, count.index)}-data.vmdk"
  datacenter    = "${var.vmware_datacenter}"
  datastore     = "${var.vmware_datastore}"
  adapter_type  = "lsiLogic"
  type          = "eagerZeroedThick"
}
```

### Panic Output

```
vsphere_virtual_machine.etcd[0]: Refreshing state... (ID: Terraform/dev-etcd-general-0)
Error refreshing state: 3 error(s) occurred:

* module.etcd.vsphere_virtual_machine.etcd: 3 error(s) occurred:

* module.etcd.vsphere_virtual_machine.etcd[1]: vsphere_virtual_machine.etcd.1: unexpected EOF
* module.etcd.vsphere_virtual_machine.etcd[0]: vsphere_virtual_machine.etcd.0: unexpected EOF
* module.etcd.vsphere_virtual_machine.etcd[2]: vsphere_virtual_machine.etcd.2: unexpected EOF
* module.kube-worker.vsphere_virtual_machine.kube: 3 error(s) occurred:

* module.kube-worker.vsphere_virtual_machine.kube[1]: vsphere_virtual_machine.kube.1: unexpected EOF
* module.kube-worker.vsphere_virtual_machine.kube[0]: vsphere_virtual_machine.kube.0: unexpected EOF
* module.kube-worker.vsphere_virtual_machine.kube[2]: vsphere_virtual_machine.kube.2: unexpected EOF
* module.kube-master.vsphere_virtual_machine.kube: 3 error(s) occurred:

* module.kube-master.vsphere_virtual_machine.kube[2]: vsphere_virtual_machine.kube.2: unexpected EOF
* module.kube-master.vsphere_virtual_machine.kube[0]: vsphere_virtual_machine.kube.0: unexpected EOF
* module.kube-master.vsphere_virtual_machine.kube[1]: vsphere_virtual_machine.kube.1: unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1aa83fb]
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4:
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: goroutine 207 [running]:
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vsphere.resourceVSphereVirtualMachineRead(0xc4201dcaf0, 0x1c7ada0, 0xc42057ccc0, 0x1, 0x2a
3e4c0)
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vsphere/vsphere/resource_vsphere_virtual_machi
ne.go:1191 +0x240b
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4204fcf60, 0xc4
2007ee10, 0x1c7ada0, 0xc42057ccc0, 0xc420255808, 0xc420164a01, 0x80001082052)
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/
helper/schema/resource.go:321 +0x199
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4205640e0, 0xc4
2007edc0, 0xc42007ee10, 0x302d458, 0x0, 0x22)
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/
helper/schema/provider.go:284 +0x9a
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc42061a24
0, 0xc4204bfee0, 0xc4204bffd0, 0x0, 0x0)
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vsphere/vendor/github.com/hashicorp/terraform/
plugin/resource_provider.go:510 +0x4e
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: reflect.Value.call(0xc420057b00, 0xc4206360a0, 0x13, 0x1ee2ff5, 0x4, 0xc420164f20, 0x3, 0x3, 0xc4203cbf28, 0x2, ...)
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4:       /usr/local/go/src/reflect/value.go:434 +0x906
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: reflect.Value.Call(0xc420057b00, 0xc4206360a0, 0x13, 0xc4203cbf20, 0x3, 0x3, 0x29d3da0, 0xc4203444e0, 0xc4202c81e0)
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4:       /usr/local/go/src/reflect/value.go:302 +0xa4
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: net/rpc.(*service).call(0xc420055ac0, 0xc420180050, 0xc4202be070, 0xc420487200, 0xc42047c500, 0x1ba2a60, 0xc4204bfee0, 0x16, 0x1ba2aa0, 0xc4204bffd0
, ...)
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4:       /usr/local/go/src/net/rpc/server.go:381 +0x142
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: created by net/rpc.(*Server).ServeCodec
2017-10-20T15:32:59.834+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4:       /usr/local/go/src/net/rpc/server.go:475 +0x36b
2017/10/20 15:32:59 [ERROR] root.kube-worker: eval: *terraform.EvalRefresh, err: vsphere_virtual_machine.kube.1: unexpected EOF
2017/10/20 15:32:59 [ERROR] root.kube-worker: eval: *terraform.EvalSequence, err: vsphere_virtual_machine.kube.1: unexpected EOF
2017/10/20 15:32:59 [TRACE] [walkRefresh] Exiting eval tree: module.kube-worker.vsphere_virtual_machine.kube[1]
2017/10/20 15:32:59 [ERROR] root.etcd: eval: *terraform.EvalRefresh, err: vsphere_virtual_machine.etcd.1: unexpected EOF
2017/10/20 15:32:59 [ERROR] root.etcd: eval: *terraform.EvalSequence, err: vsphere_virtual_machine.etcd.1: unexpected EOF
```

### Expected Behavior

Terraform should show the difference to be applied.

### Actual Behavior

Terraform crashed with panic

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids

No issue when initially deployed from scratch. Changing nothing, wait for a while (in our case the second attempt is after a day) and run `terraform plan` again, it crashes.

We have vMotion enabled.

**Comment by vancluever** [comment] 2017-10-20 15:59
Thank you @javefang! As I been mentioning in a number of recent issues, we are starting work on a major factor of this resource, so I am rationing the time I spend on maintenance efforts on the current version, but crashes definitely warrant maintenance, so I will look into this and put out a release when we have it fixed.

Stay tuned!

**Comment by javefang** [comment] 2017-10-20 16:06
Thank you @vancluever! To throw my 1 penny finding, I feel like this is related to vMotion as nothing has changed between "not crash" and "crash". I just simply ran "terraform plan" again after a while when it started to crash.

**Comment by vancluever** [comment] 2017-10-20 19:56
Hey @javefang, I'm trying to reproduce here, but am having some trouble - would you be able to share your network configuration with me? Namely, anything that would cause `IpConfig` to be absent even though there is an entry in the guest networking info for it?

I've tried:

* Completely downed interface
* Interface up with no IPv4 address assigned (`ifconfig IFNAME up`)
* Disabling IPv6 so it has no IPv4 or IPv6 addresses assigned (using sysctl)

Also of note might be if the machine has any dummy interfaces or what not.

Thanks!

**Comment by javefang** [comment] 2017-10-22 19:55
Hi @vancluever, this are 4 network adapters on those VMs

1. lo
2. ens160 (the main network device)
3. docker0 (this is a Kubernetes worker so it runs Docker on it)
4. califf08e1cd27a (we use Calico to provide overlay network inside the cluster, I believe this is a virtual adapter created by it)

```
califf08e1cd27a: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::8e1:48ff:fe33:76d7  prefixlen 64  scopeid 0x20<link>
        ether 0a:e1:48:33:76:d7  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:ef:41:d6:fd  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens160: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.106.102.66  netmask 255.255.254.0  broadcast 10.106.103.255
        inet6 fe80::250:56ff:fe99:a160  prefixlen 64  scopeid 0x20<link>
        ether 00:50:56:99:a1:60  txqueuelen 1000  (Ethernet)
        RX packets 10136518  bytes 5608517320 (5.2 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 7089451  bytes 1842901129 (1.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 6526193  bytes 6017387564 (5.6 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6526193  bytes 6017387564 (5.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
I'm waiting for this to happen again so I can gather more debug data. 

Thanks!

**Comment by rismoney** [comment] 2017-10-24 12:41
Can TF do better than EOF errors and provide failed API call as part of stderr?

**Comment by vancluever** [comment] 2018-02-26 16:19
Hello! 

This issue details items mainly relevant to the vSphere provider before the 1.x release. Since the release of the vSphere 1.x release, several features have been added and several bugs have been fixed, namely having to do with the features and functionality of the `vsphere_virtual_machine` resource.

As there is a very good chance that any problems or requests described in this issue have been corrected or implemented, we are closing this issue now. However, if you are still having problems after updating your Terraform and vSphere providers to the latest version, please open a new issue.

For more details on the state of the provider now, please check out these links:

[vSphere Provider Documentation Index](https://www.terraform.io/docs/providers/vsphere/index.html)
[`vsphere_virtual_machine` Resource Documentation](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html)
[Blog post detailing an end-to-end setup using the 1.x releases](https://www.hashicorp.com/blog/a-re-introduction-to-the-terraform-vsphere-provider)

Thanks!

**Closed by vancluever** 2018-02-26 16:19 UTC
Labels: bug, crash
